paramak/extruded_circle_shape.py
paramak/extruded_mixed_shape.py
paramak/extruded_spline_shape.py
paramak/extruded_straight_shape.py
paramak/parametric_shapes/__init__.py
paramak/parametric_shapes/center_column_cylinder.py
paramak/parametric_shapes/center_column_flat_top_hyperbola.py
paramak/parametric_shapes/center_column_hyperbola.py
paramak/parametric_shapes/center_column_plasma_dependant.py
paramak/parametric_shapes/divertor_block.py
paramak/parametric_shapes/poloidal_field_coil.py
paramak/parametric_shapes/poloidal_field_coil_case.py
paramak/parametric_shapes/tokamak_plasma.py
paramak/rotate_circle_shape.py
paramak/rotate_mixed_shape.py
paramak/rotate_spline_shape.py
paramak/rotate_straight_shape.py
tests/test_ExtrudeCircleShape.py
tests/test_ExtrudeMixedShape.py
tests/test_ExtrudeSplineShape.py
tests/test_RotateCircleShape.py
tests/test_RotateMixedShape.py
tests/test_RotateSplineShape.py

Pull request for adding a 'dirty flag' feature to solid creation.
Solids are created with a unique hash_value. create_solid() is only recalled if shape attributes are changed

Add shape solid flag

---

paramak/extruded_mixed_shape.py
paramak/rotate_mixed_shape.py
paramak/shape.py
tests/test_ExtrudeMixedShape.py
tests/test_RotateMixedShape.py

This adds support for circles to the ExtrudeMixedShape and RotateMixedShape and a couple of tests to check volumes are constructed

Add circle to mixed shapes

---

paramak/parametric_shapes/center_column_flat_top_hyperbola.py
paramak/parametric_shapes/center_column_hyperbola.py
paramak/parametric_shapes/center_column_plasma_dependant.py

Added endpoint = startpoint to parametric shapes. This is required as the points setter is overwritten in parametric shape classes to accommodate the find_points() methods.

added required endpoint

---

paramak/parametric_components/tokamak_plasma.py

This PR includes an upgrade of the `Plasma()` component which is now based on parametric equations.
These equations take 4 geometrical parameters namely minor and major radii, elongation and triangularity.
**Usage**
```python
import paramak
plasma = paramak.Plasma(minor_radius=200, major_radius=620, triangularity=0.55, elongation=1.85, rotation_angle=180)
plasma.solid
```

Enhancement: updating the Plasma() component

---

docs/source/example_neutronics_simulations.rst
docs/source/index.rst
docs/source/tests.rst
examples/example_parametric_components/make_all_parametric_components.py
examples/example_parametric_components/make_all_parametric_components_images_for_docs.py
paramak/shape.py

This adds a few parts to the read the docs
parametric reactors now have an entry in the docs
the neutronics example has been renamed
shape.export_stp can now check to see if the stp_filename property is uses in the event that the filename argument in none
added a script to generate svg images for the documentation, this required a reworking of the make_all_parametric_componets.py

updated a few names in the docs and got svg export with stp_filename

---

paramak/parametric_components/tokamak_plasma.py
tests/test_ParametricComponents.py

This PR includes an extension of the `Plasma()` object by adding several attributes:
`Plasma().configuration` determines if the plasma is non-null, single-null or double-null
`Plasma().lower_x_point` (resp. `Plasma().upper_x_point`) contains the (x, y) coordinates of the lower (resp.upper) X point and is None if there isn't any lower (resp. upper) X point.
This does not change the geometrical aspect of the plasma.
```python
import paramak
myPlasma = paramak.Plasma(configuration="single-null")
print(myPlasma.lower_x_points, myPlasma.upper_x_points)
```
Some tests were added and existing ones were renamed

Add plasma X points locations to Plasma()

---

paramak/parametric_reactors/ball_reactor.py
paramak/parametric_reactors/submersion_ball_reactor.py
paramak/reactor.py
paramak/shape.py
tests/test_BallReactor.py
tests/test_Reactor.py
tests/test_SubmersionBallReactor.py

This PR adds tet_mesh to the neutronics description and converts the BallReactor arguments into radial thicknesses
The tet_mesh addition allows us to streamline the tet mesh creation for components or shapes in trelis as we can specific the tet mesh command when creating the shape/ component
The new BallReactor arguments make it much harder for users to create reactors that overlap. Previously the user could make reactors where the plasma overlaps the center coulmn but now due to the shift to a radial build approach this is protected against.
The BallReactor still needs improved divertors, magnets etc and the submersion reactor needs to be converted to this linear radial build input form but that can be done in another PR

Improving parametric reactors

---

paramak/reactor.py
tests/test_BallReactor.py
tests/test_Reactor.py

This adds .svg export to parametric reactors, the export_svg doesn't currently support a view orientation so the default is XY which means the svg images are not ideal for the XZ based reactor.
Future solutions for this might come from CADquery or the reactor can be rotated

added svg export and tests

---

paramak/reactor.py
paramak/shape.py

**This PR aims to introduce ways for exporting information (readable by humans) on physical groups in step files.**
If a user wants to use the generated step file of say a `BlanketConstantThicknessFP()` in a FE program, he/she needs to guess (or trial/error):
- the number of physical groups (physical surfaces and volumes)
- which id (already generated by CADquery) corresponds to which physical group
Classes inheriting from `Shape()` can now have an attribute called `look_up_table` which contains a list of dicts with physical groups infos: 
```python
look_up_table = [
{"dim": 3, "id": 1, "name": "inside_volume"},
{"dim": 2, "id": 1, "name": "top_surface"},
{"dim": 2, "id": 2, "name": "inner_surface"},
{"dim": 2, "id": 2, "name": "outer_surface"},
]
```
Above, the relations between "id" and …

Building block of FE simulations: look-up table for exporting physical groups

---

examples/example_parametric_reactors/make_parametric_ball_reactor.py
paramak/parametric_reactors/ball_reactor.py

This PR adds a first wall to the ```BallReactor``` model
```
import paramak
my_reactor = paramak.BallReactor(
inner_bore_radial_thickness=50,
inboard_tf_leg_radial_thickness = 200,
center_column_radial_thickness= 50,
inner_plasma_gap_radial_thickness = 50,
plasma_radial_thickness = 100,
outer_plasma_gap_radial_thickness = 50,
firstwall_radial_thickness=5,
blanket_radial_thickness=100,
elongation=2,
triangularity=0.55,
number_of_tf_coils=16,
)
my_reactor.export_stp()
```
A rear wall should be added, improved unit tests and an parameterized divertor

added firstwall

---

paramak/parametric_reactors/ball_reactor.py

This PR makes sure that all the components created match the reactor ```rotation_angle```.
For the inboard TF coils this option is not yet controllable from the parametric component
Therefore a cylindrical wedge has been added that cuts the offending solid
The before an after screenshots show more clearly what has been fixed
This will also come in useful for the TF coils later

added cutting cylinder

---

examples/example_parametric_reactors/make_parametric_ball_reactor.py
paramak/reactor.py
tests/test_Reactor.py

When exporting a neutronics_description (which is needed to make a neutronics model later on) users now have the ability to not export the plasma.
This is useful for the neutronics simulation as the plasma is typically left out of the model as it has negligible impact on the simulation result but has a detrimental impact on simulation speed and model size. This is due to the large number of facetets needed in a plasma shape and the low number density of atoms in a plasma
current behaviour
```export_neutronics_description()```  - this exports every entry (stp filename and material tag)
new behavior
```export_neutronics_description(include_plasma=False)```- this exports every entry (stp filename and material tag) apart from the plasma
tests and docstrings have been updated
The default is to …

added optional plasma and tests

---

paramak/parametric_components/blanket_constant_thickness_fp.py
tests/test_ParametricComponents.py

This PR partially fixes issue #86 and a geometry issue in `BlanketConstantThicknessFP()`.
- refactoring
- new test
- When applying full coverage (`start_angle` = `stop_angle`) **AND** full rotation (`rotation_angle=360`) method `export_stp()` still crashes #86

Full coverage blanket fix: The Revenge

---

examples/example_neutronics_simulations/parametric_shape_neutronics_model.py
examples/example_parametric_shapes/make_can_reactor_from_parameters.py
examples/example_parametric_shapes/make_can_reactor_from_points.py
paramak/parametric_reactors/ball_reactor.py
paramak/parametric_reactors/submersion_ball_reactor.py
paramak/reactor.py
paramak/shape.py
tests/test_Reactor.py

This PR allows the shapes and components in a reactor to be set when the reactor is initialized.
The old method was to uses ```add_shape_or_component``` for each entry to be added.
The method allows the shapes_and_componets to be passed as an argument on construction
The Reactor.stp_filenames, Reactor.material_tags, Reactor.tet_meshes have all been moved to getter an setter methods which scan through the components.
The problem with the old method was that users could add shapes directly to the Reactor.shapes_and_components attribute by passing the add_shape_or_component method and therefore getting the stp_filenames and material_tags out of sync with the object. Also the new method saves a line or two of code in some cases.
old method
my_reactor = paramak.Reactor() …

Reactor refactor

---

paramak/parametric_components/blanket_constant_thickness_fp.py
tests/test_ParametricComponents.py

This PR includes a new method for adding physical groups (with names) to `paramak.BlanketConstantThicknessFP()`.
The surfaces are labelled as shown below:
```python
from paramak import BlanketConstantThicknessFP
my_shape = BlanketConstantThicknessFP(100, start_angle=0, stop_angle=180, rotation_angle=180)
my_shape.export_stp('blanket.stp')
my_shape.export_physical_groups('blanket.json')
```
If `rotation_angle` = 360 then `'left_section'` and `'right_section'` don't exist.
These physical groups can then be read in GMSH  as described in #83.
-  If `start_angle` = `stop_angle` mod 2*k*pi, `inner_section `and `outer_section ` are not be exported since they don't normally exist. Though `inner_section `and `outer_section ` exist due this bug #86

Physical groups for BlanketConstantThicknessFP

---

docs/source/conf.py
paramak/parametric_shapes/rotate_spline_shape.py

This PR adds the napoleon dependency to sphinx, allowing both google-style and sphinx-style docstrings to be used in the same project for a local doc build. This PR will be merged to test whether readthedocs will successfully build the documentation with mixed docstrings. This is in reference to issue #75

Add google style support

---

examples/example_neutronics_simulations/parametric_ball_reactor_neutronics_models.py
examples/example_parametric_reactors/make_parametric_ball_reactor.py
paramak/parametric_reactors/ball_reactor.py
paramak/utils.py

This adds a variation of the divertor to the ball_reactor. In the event that the divertor_radial_thickness is larger than the vertical space between the blanket and the center column then the divertor will curve around on the same arc as the blanket. The blanket, first wall and blanekt rear wall will be cut with the divertor to ensure there is no overlap.
ToDo
Add a regular divertor if the gap is equal to the divertor_radial_thickness

added divertor that curves around if needed

---

examples/example_parametric_reactors/make_parametric_ball_reactor.py
paramak/parametric_reactors/ball_reactor.py

This updates the BallReactor
In the event that the divertor gap and the divertor radial thickness are the same then this no longer crashes

Fixed ball reactor tests

---

paramak/parametric_reactors/ball_reactor.py
tests/test_BallReactor.py

This PR adds TF and PF coils to the BallReactor parametric reactor class 
Extra BallReactor parameters have been introduced
There are all optional so if the user does not want magnets then the BallReactor will still be made without them
pf_coil_radial_thicknesses = [50,50,50,50],
pf_coil_vertical_thicknesses = [50,50,50,50],
pf_coil_to_rear_blanket_radial_gap=50,
pf_coil_to_tf_coil_radial_gap = 50,
tf_coil_radial_thickness = 100,
tf_coil_poloidal_thickness=50
Docstrings and tests (that check model creation only) have been added
ToDo
PF coils are automatically positioned by spreading them out evenly in the Z direction. In another pull request the option to allow the user to specify the position would be a nice upgrade

added optional pf and tf coils

---

paramak/parametric_components/divertor_ITER.py

This PR extends the documentation for the `ITERtypeDivertor` by adding docstrings to the functions.

Extend documentation divertor

---

tests/test_BallReactor.py
tests/test_ExtrudeMixedShape.py
tests/test_Reactor.py
tests/test_RotateMixedShape.py
tests/test_Shape.py

This PR is related to #136 and increase the coverage above 90% 🚀 💚 .
Tests have been added to : 
- `Shape`
- `ExtrudeMixedShape`
- `RotateMixedShape`
- `Reactor`
- `BallReactor`
Known errors:
- `export_3d_image` method breaks for all objects (shape or reactor)
ToDo:
- methods like `export_3d_image`, `export_stp`, `export_stl` and all should be tested within the `Shape` test suite and not as currently in the `ExtrudeMixedShape` or `RotateMixedShape` test suites

More tests for greener badge

---

README.md

The readme for the main branch should point to the test suite for the main branch. It was pointing to the develop branch (which is often in flux and broken)

change circle ci badge to main

---

README.md
docs/source/index.rst

PR to add description of parametric reactor usage to documentation. Tried to remove the toctree on the title page but this is required. Ideally, need to find a way to remove this from the main landing page but still have the links in the sidebar of readthedocs. This will be dealt with in a future PR.

Add usage parametric reactors

---

paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/parametric_shapes/rotate_spline_shape.py
paramak/parametric_shapes/rotate_straight_shape.py
paramak/reactor.py
tests/test_Reactor.py

This fixes a few mistakes from an earlier PR.
The addition of another test showed that duplicate stl_filenames were not being detected
This PR adds a simple test that checks for duplicate stl filenames the different parametric shapes are added

added stl duplication filename checks

---

paramak/reactor.py

Added in the body of the gist. I took the liberty of moving the attempted PyMOAB import into that method. With the import at the top, the method would return the error "core not found" which is a little esoteric. Now the method will raise an `ImportError` if called when PyMOAB is not installed. 
As I mentioned on slack, PyMOAB isn't in the CI so I haven't been able to verify the test you've added. I'd be happy to add it into the CI image before merging to make sure it works though. Just let me know!

Adding body of the Reactor.export_h5m method

---

paramak/parametric_components/blanket_constant_thickness_arc_h.py
paramak/parametric_components/blanket_constant_thickness_arc_v.py
paramak/parametric_components/blanket_fp.py
paramak/parametric_components/center_column_circular.py
paramak/parametric_components/center_column_cylinder.py
paramak/parametric_components/center_column_flat_top_circular.py
paramak/parametric_components/center_column_flat_top_hyperbola.py
paramak/parametric_components/center_column_hyperbola.py
paramak/parametric_components/center_column_plasma_dependant.py
paramak/parametric_components/inner_tf_coils_circular.py
paramak/parametric_components/inner_tf_coils_flat.py
paramak/parametric_components/poloidal_field_coil.py
paramak/parametric_components/poloidal_field_coil_case.py
paramak/parametric_components/poloidal_field_coil_case_fc.py
paramak/parametric_components/tokamak_plasma.py
paramak/parametric_components/tokamak_plasma_from_points.py
paramak/parametric_components/tokamak_plasma_plasmaboundaries.py
paramak/parametric_components/toroidal_field_coil_coat_hanger.py
paramak/parametric_components/toroidal_field_coil_rectangle.py
paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/parametric_shapes/rotate_spline_shape.py
paramak/parametric_shapes/rotate_straight_shape.py

PR to update hash_value calculation to use automatically identified class parameters. hash_value parameter has also been removed from the default_dict to prevent specification by a user upon construction.
Resolves #171

Update hash value

---

.github/workflows/autopep8.yml

PR to add make_faceteted_neutronics_model.py to the list of files to be ignored by autopep8. This resolves #186

added trelis file to be ignored

---

.github/workflows/autopep8.yml

PR #189 used the full filepath of the trelis script from the base directory of the paramak. Through local testing it was found that only the filename was required

fixed trelis script exclusion filepath

---

.github/workflows/autopep8.yml
examples/example_neutronics_simulations/make_faceteted_neutronics_model.py

This is an alternative solution to #187 for fixing the trelis make_faceteted_neutronics_model.py script. This does not require a rollback of the autopep8 formatting. Resolves #186

added newline character

---

paramak/parametric_reactors/ball_reactor.py
paramak/parametric_reactors/single_null_ball_reactor.py
tests/test_BallReactor.py

This PR changes the ball reactor to use parameters stored as attributes of the instance, i.e. self._attributes, rather than local parameters. This allows all parameters to be passed between the methods via self, rather than in large lists of attributes and return statements

Convert to self

---

paramak/parametric_reactors/single_null_submersion_reactor.py
paramak/parametric_reactors/submersion_reactor.py

This PR changes the submersion ball reactor to use parameters stored as attributes of the instance, i.e. self._attributes, rather than local parameters. This allows all parameters to be passed between the methods via self, rather than in large lists of attributes and return statements

Convert sub to self

---

examples/example_parametric_reactors/make_render.py

This moves some code from the reactor.py and shape.py which was incompatible with docker into a stand alone script so that renderings can still be made but the docker based tests can also pass

made example render script

---

tests/test_BallReactor.py

updates test_BallReactor.py script to use rotation_angle=359. This prevents the construction error outlined in #216. This is a temporary fix until #216 is resolved

updated rotation angle

---

paramak/__init__.py
paramak/parametric_components/blanket_fp.py
paramak/parametric_components/toroidal_field_coil_princeton_d.py
paramak/parametric_components/toroidal_field_coil_triple_arc.py
paramak/parametric_reactors/ball_reactor.py
paramak/parametric_reactors/single_null_ball_reactor.py
paramak/parametric_reactors/single_null_submersion_reactor.py
paramak/parametric_reactors/submersion_reactor.py
tests/test_SubmersionTokamak.py

PR which prints warning message if BallReactor or SubmersionTokamak (or single null versions) rotation_angle = 360. Also updates submersion reactor tests to use rotation_angle=359.

Add rotation angle warning

---

docs/source/paramak.parametric_components.rst

PR uses the autoclass method to inherit specific classes from the script. This allows the two types of ITER divertor to be separated in the documentation. Resolves #184

separated domed and no dome ITER divertor

---

.github/workflows/python-publish.yml

This makes the PyPi update only happen on push and it tries to bump the version number automatically

pypi_update_on_push_only

---

paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/parametric_shapes/rotate_spline_shape.py
paramak/parametric_shapes/rotate_straight_shape.py

PR to move the hash_value parameter to default dict. This removes hash_value from the init constructor, but allows it to be passed as a kwarg.
See #236 for further details.
What do you think @Shimwell ?

moved hash_value to default_dict

---

docs/source/paramak.parametric_reactors.rst

This adds a few reactor images to the docs and also removes the height setting for reactor images (it was causing images to be squashed). Ideally there would be a couple more svg images but that can come in a later PR
If this is a relatively small PR that does not interfere with the source code

added two reactor images and removed height setting

---

examples/example_parametric_components/make_all_parametric_components.py
paramak/parametric_components/blanket_constant_thickness_arc_h.py
paramak/parametric_components/blanket_constant_thickness_arc_v.py
paramak/parametric_components/blanket_fp.py
paramak/parametric_components/center_column_circular.py
paramak/parametric_components/center_column_cylinder.py
paramak/parametric_components/center_column_flat_top_circular.py
paramak/parametric_components/center_column_flat_top_hyperbola.py
paramak/parametric_components/center_column_hyperbola.py
paramak/parametric_components/center_column_plasma_dependant.py
paramak/parametric_components/divertor_ITER.py
paramak/parametric_components/inner_tf_coils_circular.py
paramak/parametric_components/inner_tf_coils_flat.py
paramak/parametric_components/poloidal_field_coil.py
paramak/parametric_components/poloidal_field_coil_case.py
paramak/parametric_components/poloidal_field_coil_case_fc.py
paramak/parametric_components/tokamak_plasma_from_points.py
paramak/parametric_components/tokamak_plasma_plasmaboundaries.py
paramak/parametric_components/toroidal_field_coil_coat_hanger.py
paramak/parametric_components/toroidal_field_coil_princeton_d.py
paramak/parametric_components/toroidal_field_coil_rectangle.py
paramak/parametric_components/toroidal_field_coil_triple_arc.py

PR which removes the points getter/setter pair specified for each parametric component which overwrites the getter/setter pair in shape.py. As mentioned in #253, find_points() can be called directly outside a getter/setter and the points are checked for errors. 
A similar solution could be implemented for parametric components which overwrite the azimuth_placement_angle getter/setter pair when a method is called to calculate these angles.

Parametric component points

---

paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/parametric_shapes/rotate_spline_shape.py
paramak/parametric_shapes/rotate_straight_shape.py
paramak/shape.py

PR which moves the boolean operations of cut, union and intersect into shape.py. create_solid() for each parametric_shape calls perform_boolean_operations() method which performs the operations if any of the boolean attributes of the Shape object have been set.

moved boolean operations into shape

---

tests/test_RotateSplineShape.py
tests/test_RotateStraightShape.py

This very small PR adds tests which check that `RotateSplineShape` and `RotateStraightShape `can accept iterables for `azimuth_placement_angles`. I ran the coverage locally and got 96%! 🟢 

added tests for azimuth_placement_angles as iterables

---

paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/parametric_shapes/rotate_spline_shape.py
paramak/parametric_shapes/rotate_straight_shape.py
paramak/shape.py

Code refactoring to move cut, union and intersect getter/setter pairs into shape.py and having each parametric shape inherit. This removes the need for boolean method getter/setter pairs in each parametric shape.
Ideally, the boolean commands for performing the operations should be moved out of create_solid() and into a common method in shape.py which is used in create_solid() by each parametric shape. This also allows the boolean operations to be used by Shape.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

moved cut union intersect into shape

---

docs/source/example_parametric_components.rst
docs/source/paramak.parametric_components.rst
examples/example_parametric_components/make_demo_style_blankets.py
examples/example_parametric_components/make_firstwall_for_neutron_wall_loading.py
examples/example_parametric_reactors/make_all_parametric_reactors_images_for_docs.py
paramak/__init__.py
paramak/parametric_components/poloidal_segmenter.py
paramak/parametric_shapes/rotate_straight_shape.py
paramak/reactor.py
paramak/utils.py
tests/test_ParametricComponents.py
tests/test_examples.py

This adds a PoloidalSegmenter component that can be used to segment up other components poloidally
Future use of this PoloidalSegmenter would be to use an intersect method together with another component to segment the component up poloidally. This is useful for neutron wall loading tallies where the number of neutrons passing through the first wall is needed as a function of poloidal angle
There is still lots to do to make this complete. 
- …

added segments maker feature

---

examples/example_parametric_components/make_magnet_set.py
paramak/parametric_reactors/ball_reactor.py
paramak/parametric_reactors/submersion_reactor.py
paramak/reactor.py
tests/test_BallReactor.py
tests/test_SubmersionTokamak.py
tests/test_examples.py

This PR aims to provide an example set of magnets TF and PF for users that are just keen to make magnet geometry.
This update makes use of the new PoloidalFieldCoilSet() and PoloidalFieldCoilCaseSetFC() to reduce the number of lines in the draft magnet set example, in the submersion reactor and the ball reactor
Todo
- Add documentation
- Add tests
When  azimuth angles or offset can be user controled then rotate the InnerTfCoilsFlat by 0.5*(360/number of tf coils)
When the coordinates of the inboard connections of the ToroidalFieldCoilPrincetonD are known (perhaps due to another PR) then ...
- Add inboard TF coil legs
- Cut the existing InnerTfCoilsFlat with the new TF coil legs

Improved magnet set example and code reduction using PoloidalFieldCoilSet

---

paramak/parametric_components/blanket_fp.py
tests/test_ParametricComponents.py

This PR includes a patch for the `BlanketFP` class.
- Bug fixing: #283 #250
- Feature: variable offset from plasma #251 
Usage:
```python
import paramak
import numpy as np
def fun(theta):
conversion_factor = 2 * np.pi / 360
return 20 + 20*np.sin(theta/conversion_factor)
blanket = paramak.BlanketFP(
minor_radius=150.0,
major_radius=450.0,
triangularity=0.55,
elongation=2.0,
thickness=50,
offset_from_plasma=fun,
start_angle=0,
stop_angle=160,
rotation_angle=180
)
blanket.export_stp('blanquette.stp')
```

BlanketFP patch: variable offset + bugfixing

---

paramak/parametric_components/blanket_fp.py

Currently BlanketFP accepts a tuple for offset_from_plasma and thickness. This tiny PR adds support for lists (still of length 2). Lists behave the same as tuples in this case and I think lists are generally more used by users.
- [ x Pep8 applied

adding list to offset and thickness to BlanketFP

---

paramak/parametric_components/blanket_constant_thickness_arc_h.py
paramak/parametric_components/blanket_constant_thickness_arc_v.py
paramak/parametric_components/blanket_fp.py
paramak/parametric_components/center_column_circular.py
paramak/parametric_components/center_column_cylinder.py
paramak/parametric_components/center_column_flat_top_circular.py
paramak/parametric_components/center_column_flat_top_hyperbola.py
paramak/parametric_components/center_column_hyperbola.py
paramak/parametric_components/center_column_plasma_dependant.py
paramak/parametric_components/divertor_ITER.py
paramak/parametric_components/inner_tf_coils_circular.py
paramak/parametric_components/inner_tf_coils_flat.py
paramak/parametric_components/poloidal_field_coil.py
paramak/parametric_components/poloidal_field_coil_case.py
paramak/parametric_components/poloidal_field_coil_case_fc.py
paramak/parametric_components/poloidal_field_coil_case_set.py
paramak/parametric_components/poloidal_field_coil_case_set_fc.py
paramak/parametric_components/poloidal_field_coil_set.py
paramak/parametric_components/poloidal_segmenter.py
paramak/parametric_components/tokamak_plasma.py
paramak/parametric_components/tokamak_plasma_from_points.py
paramak/parametric_components/tokamak_plasma_plasmaboundaries.py
paramak/parametric_components/toroidal_field_coil_coat_hanger.py
paramak/parametric_components/toroidal_field_coil_princeton_d.py
paramak/parametric_components/toroidal_field_coil_rectangle.py
paramak/parametric_components/toroidal_field_coil_triple_arc.py
paramak/shape.py

Following suggestions from @RemiTheWarrior , a conditional call of find_points() has been added to the points getter in the Shape class. This removes the need to specify new points getters and setters in each parametric component class as find_points() is conditionally called as part of the Shape getters and setters. 
As the points setter also adds final point = start point automatically, having this inheritance removes the need to specify the end point when making parametric components.
find_points() is called conditionally meaning classes with no find_points() method, such as the parametric shapes, are unaffected
_Put an `x` in the boxes that apply. You can also fill these out after …

Fix parametric components shape

---

paramak/parametric_components/blanket_fp.py
paramak/parametric_reactors/center_column_study_reactor.py
tests/test_CenterColumnStudyReactor.py

A new feature for in BlanketFP that accepts a list of offsets_from_plasma allows the vertical build for the CenterColumnStudyReactor to be made from a simple list. This has been implemented and is and the vertical build is now working for CenterColumnStudyReactor. 
Docstrings have also been updated on BlanketFP
Perhaps other parametric reactors can be improved to utilise this feature.

Adding vertical build to center column study

---

paramak/parametric_components/blanket_constant_thickness_arc_h.py
paramak/parametric_components/blanket_constant_thickness_arc_v.py
paramak/parametric_components/blanket_fp.py
paramak/parametric_components/center_column_circular.py
paramak/parametric_components/center_column_cylinder.py
paramak/parametric_components/center_column_flat_top_circular.py
paramak/parametric_components/center_column_flat_top_hyperbola.py
paramak/parametric_components/center_column_hyperbola.py
paramak/parametric_components/center_column_plasma_dependant.py
paramak/parametric_components/divertor_ITER.py
paramak/parametric_components/inner_tf_coils_circular.py
paramak/parametric_components/inner_tf_coils_flat.py
paramak/parametric_components/poloidal_field_coil.py
paramak/parametric_components/poloidal_field_coil_case.py
paramak/parametric_components/poloidal_field_coil_case_fc.py
paramak/parametric_components/poloidal_field_coil_case_set.py
paramak/parametric_components/poloidal_field_coil_case_set_fc.py
paramak/parametric_components/poloidal_field_coil_set.py
paramak/parametric_components/poloidal_segmenter.py
paramak/parametric_components/tokamak_plasma.py
paramak/parametric_components/tokamak_plasma_from_points.py
paramak/parametric_components/tokamak_plasma_plasmaboundaries.py
paramak/parametric_components/toroidal_field_coil_coat_hanger.py
paramak/parametric_components/toroidal_field_coil_princeton_d.py
paramak/parametric_components/toroidal_field_coil_rectangle.py
paramak/parametric_components/toroidal_field_coil_triple_arc.py
paramak/shape.py
tests/test_ParametricComponents.py

In a previous PR, the points setter was removed from all parametric components in an attempt to reduce the total number of lines of code. This did not affect initial construction as find_points() was called explicitly upon construction. However, find_points() was no longer being called upon reconstruction of the solid meaning that attributes could be changed after initial construction, but the points used to construct the shape were not affected, meaning the changes were useless.
This PR adds a conditional call to find_points() to the points setter in Shape which is inherited by all parametric shapes and components. The call is conditional meaning only classes which have the a find_points() method will call this method, allowing the points to be re-calculated correctly after attribute …

fix solid reconstruction after attribute alteration

---

paramak/parametric_components/inner_tf_coils_circular.py
paramak/parametric_components/inner_tf_coils_flat.py
tests/test_ParametricComponents.py

Adds azimuth_start_angle attribute to inner tf coil parametric components which allows the tf coils to be rotated by a given amount.

Tf coil offset angle

---

docs/source/paramak.parametric_components.rst
examples/example_parametric_components/make_all_parametric_components.py
examples/example_parametric_components/make_magnet_set.py
paramak/parametric_components/toroidal_field_coil_princeton_d.py
tests/test_ParametricComponents.py

This PR makes use of the new azimuth_start_angle in the InnerTfCoilsFlat parametric component to line up the TF coils and the inner TF coil cases
Also this adds the inner tf coil leg to the tf coil magnets for ToroidalFieldCoilPrincetonD, perhaps this can be done for the other magnets
The make_mangnet_example is not missing the tests, docs, rotation angle and the wedge cutter to finish the example
I've also tried to document the TF coil with a few more diagrams, see #310 
ToDo
For the magnet example an image is missing, tests are missing and the rotation angle parameter is missing

added inner leg to ToroidalFieldCoilPrincetonD

---

paramak/parametric_components/cutting_wedge_fs.py
paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/parametric_shapes/rotate_spline_shape.py
paramak/parametric_shapes/rotate_straight_shape.py

PR which solves the discrepancy in placement between iterable and non-iterable azimuthal placement angles. Error in codes resulted in azimuthal placements occurring in opposite directions (clockwise/anticlockwise) depending on whether azimuthal_placement_angle was given as a single number or iterable. azimuthal placement should occur in the same sense as rotation_angle.
This PR also fixes CuttingWedgeFS with respect to this fix.
If this is a …

fix azimuthal placement angle sense

---

paramak/__init__.py
paramak/parametric_components/vacuum_vessel.py
paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
tests/test_ParametricComponents.py

This PR solves #339 and adds a new parametric component VacuumVessel.
The vacuum vessel is cylindrical and holes for portplugs can be made in it.
The ports section can be circular or rectangular. Rectangular ports can be filleted by specifying a fillet radius. The rotated ports from #337 can also be added.
Usage:
```python
import paramak
vessel = paramak.VacuumVessel(
height=2, inner_radius=1, thickness=0.2,
)
vessel.export_stp('vessel.stp')
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …

New component: Vacuum Vessel with ports

---

paramak/__init__.py
paramak/parametric_components/port_cutters.py
setup.py
tests/test_ParametricComponents.py
tests/test_parametric_components/test_PortCutterRotated.py

This issue solves #347 
Usage:
```python
from paramak import RectangularPortCutter, CircularPortCutter, VacuumVessel, PortCutterRotated
cutter1 = RectangularPortCutter(distance=3, z_pos=0, height=0.2, width=0.4, fillet_radius=0.01)
cutter2 = CircularPortCutter(distance=3, z_pos=0.25, radius=0.1, azimuth_placement_angle=45)
cutter5 =PortCutterRotated((0, 0), azimuth_placement_angle=-90, rotation_angle=10, fillet_radius=0.05)
vessel = VacuumVessel(1, 1, 0.1)
vessel.cut = [cutter1, cutter2, cutter5]
vessel.export_stl('vessel.stl')
```
This PR also adds the possibility to fillet the PortCutterRotated shape.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. …

New components: RectangularPortCutter and CircularPortCutter

---

paramak/parametric_components/inboard_firstwall_fccs.py
tests/test_parametric_components/test_InboardFirstwallFCCS.py

This fixed #374.
In InboardFirstwallFCCS, instead of overwritting the create_solid method, the find_points method is overwritten.
Therefore, the boolean operations and the azimuth placement angle can be set.
2 unit tests have been added to catch the bugs.

Fix inboard firstwall fccs

---

paramak/parametric_components/toroidal_field_coil_coat_hanger.py
paramak/parametric_components/toroidal_field_coil_princeton_d.py
paramak/parametric_components/toroidal_field_coil_rectangle.py
paramak/parametric_components/toroidal_field_coil_triple_arc.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py

PR which adds the cutting wedge to some extrude classes, allowing rotation_angle for these classes to be specified. This allows the cutting wedge to be used in the tf coil parametric components which do not have their own create_solid() method.
I.e. calculate_wedge_cut has been added to all create_solid() methods for the extruded shapes and components.
This allows rotation_angle to be inherited from the extrude shapes, rather than specified in the extrude components, such as tf coils.
(Note. Has not yet been added to ExtrudeCircleShape as the workplane causes issues)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, …

added cutting wedge to extrude shapes and tf coils

---

docs/source/paramak.parametric_components.rst
examples/example_parametric_components/make_all_parametric_components.py
examples/example_parametric_components/make_demo_style_blankets.py
paramak/__init__.py
paramak/parametric_components/blanket_cutters_star.py
tests/test_parametric_components/test_BlanketCutterStar.py

This adds a new parametric component to the available options. This includes:
- a simple parametric component called BlanketCutterStar
- simple tests that show it can be created
- additional documentation with images. Images were added to github issue #32 along with the other documentation images
- added this component to the examples
- as a bonus was also able to refactor a small amount of code that efficiently did the same thing with a parametric shape.

New blanket cutters parametric shape

---

examples/example_parametric_components/make_demo_style_blankets.py
paramak/parametric_components/blanket_cutter_parallels.py
paramak/parametric_components/toroidal_field_coil_coat_hanger.py
paramak/parametric_components/toroidal_field_coil_rectangle.py
paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/shape.py
tests/test_parametric_components/test_BlanketCutterParallels.py

This PR makes some small changes to the new parralel blanket cutters.
- `distance` attribute is replaced by `thickness` to avoid confusion
- instead of having the create_solid method overwritten, the `.cut` attribute is used to cut the central pieces
- ToroidalFieldCoilCoatHanger, ToroidalFieldCoilRectangle refactored
- self.solid = solid is now done in `create_solid` and not in `perform_boolean_operations`
- minor pep8-ing
@Shimwell there is …

Parralel blanket cutters refac

---

paramak/parametric_components/inner_tf_coils_circular.py
paramak/parametric_components/inner_tf_coils_flat.py
paramak/shape.py
tests/test_Shape.py

This PR fixes #312 by making the rotation axis used in `shape.rotate_solid()` variable.
To this end, a new argument/attribute has been added as rotation_axis.
rotation_axis accepts a string in `["X", "Y", "Z", "-X", "-Y", "-Z", "+X", "+Y", "+Z"]`, a list of two points or `None`.
**Usage**
Default behaviour
```python
import paramak
component = paramak.ToroidalFieldCoilTripleArc(
R1=80,
h=200,
radii=(70, 100),
coverages=(60, 60),
thickness=30,
distance=30,
number_of_coils=3,
workplane="YZ"
)
component.export_svg("out.svg")
```
String for rotation_axis
```python
import paramak
component = paramak.ToroidalFieldCoilTripleArc(
R1=80,
h=200,
radii=(70, 100),
coverages=(60, 60),
thickness=30,
distance=30,
number_of_coils=3,
workplane="YZ"
)
component.rotation_axis = "X" …
```

Variable rotation axis for azimuth_placement_angle

---

paramak/parametric_neutronics/neutronics_model_from_reactor.py

This adds a tiny change that automatically deletes the summary.h5 file. This is needed as openmc can fail when it finds an existing summary.h5 file

Del summary

---

paramak/parametric_reactors/single_null_ball_reactor.py
paramak/parametric_reactors/single_null_submersion_reactor.py

This PR refactores (a bit) the single null submersion reactor and single null ball reactor by removing the initial calls of create_solids() that is already called in super initialisation.
This method is the bottleneck of the computation time and calling it twice only makes it worse.
This tiny change should decrease the total testing time for these tests by 30% ! (from 20min to 14min !!)
If this is a relatively large or complex change, kick …

30% speed up of the parametric reactors tests

---

paramak/parametric_components/toroidal_field_coil_coat_hanger.py
tests/test_parametric_components/test_ToroidalFieldCoilCoatHanger.py
tests/test_parametric_components/test_ToroidalFieldCoilPrincetonD.py
tests/test_parametric_components/test_ToroidalFieldCoilRectangle.py
tests/test_parametric_components/test_ToroidalFieldCoilTripleArc.py
tests/test_parametric_shapes/test_ExtrudeMixedShape.py
tests/test_parametric_shapes/test_ExtrudeSplineShape.py
tests/test_parametric_shapes/test_RotateCircleShape.py
tests/test_parametric_shapes/test_RotateMixedShape.py
tests/test_parametric_shapes/test_RotateSplineShape.py

PR which adds some basic face area tests for some extrude and rotate parametric shapes. Equivalent tests for swept shapes will be added as part of a different PR once sweep construction has been fixed. 
Also fixes ToroidalFieldCoilCoatHanger which did not allow azimuth_placement_angles to be recalculated after initial construction.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …

added basic area tests

---

paramak/parametric_neutronics/neutronics_model_from_reactor.py

This PR adds the ability to perform 2D mesh tallies to the neutronics simulation, the keyword mesh_tally_2D and mesh_2D_resolution have been added. to the NeutronicsModelFromReactor class.
mesh_tally_2D accepts strings for the reaction to tally
mesh_2D_resolution accepts a tuple of height and width
Some example results of the new tally for tritium production on a mesh and heating on a mesh are shown
breaking change
The heat argument is now replaced with heating
Todo
- refactoring is required to reduce the code
- make the tallies accept openmc reaction keywords "(n,Xt)", "(n,2n)", etc
- tests are needed for at least the getters and setters, perhaps local tests for the neutronics simulations

Adding 2d mesh tally

---

docs/source/paramak.parametric_reactors.rst
paramak/parametric_reactors/ball_reactor.py

While writing the paper I noticed that the vertical aspect of the BallReactor was a little lacking. Therefore I added another parameter called plasma_gap_vertical_thickness which allows the gap to be different to the outer_plasma_gap_radial_thickness.
If left as None then the plasma_gap_vertical_thickness will default to the same as outer_plasma_gap_radial_thickness
As the reactor tests are currently being rearranged on another PR I shall add tests later.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

added new vertical gap parameter to ball reactor

---

paramak/parametric_components/poloidal_field_coil_case_set.py
paramak/parametric_components/poloidal_field_coil_case_set_fc.py
tests/test_parametric_components/test_PoloidalFieldCoilCaseSet.py
tests/test_parametric_components/test_PoloidalFieldCoilCaseSetFC.py

This small addition allows pf coil case sets to be made with all the same thicknesses. Normally a list was needed for the casing_thickness but now a float is accepted and used as a constant thickness for all cases. 
This was needed so that the reactors can have a default setting of 10 for the case thickness. It  was not possible to use a list for the default setting as the number of coils would not be known.
Hence there will be another PR that adds coil casing to the submersion and the ball reactor

Allowing floats for casing thicknesses

---

tests/test_Reactor.py

PR which adds a reactor test to check that an error is raised when shapes with the same stl filename are added to a reactor object, and an stl file of the reactor tries to be exported.
Thanks @Shimwell for the suggestion.

added reactor export_stl error raise test

---

.github/workflows/dockerhub-publish-dev-cd-master.yml
Dockerfile

This PR adds some build arguments to the dockerfile so that it can be build with cq master or cq latest release
A new github actions file is also added that will automatically build and publish a tag ```ukaea/paramak:dev-cq-master```
Lastest release of cadquery stays as default

added build args to dockerfile

---

paramak/parametric_components/blanket_fp.py
tests/test_parametric_components/test_BlanketFP.py

This PR fixes the tests in BlanketFP and is a sub PR of #507 
The tests resulted in a rubbish geometry which didn't failed in the previous version of Cadquery but do in master.
Thanks to the new version of Cadquery, BlanketFP can now have a 360degree rotation and full coverage.

Fix blanketFP

---

paramak/parametric_components/blanket_fp.py
paramak/parametric_reactors/ball_reactor.py
paramak/parametric_reactors/single_null_ball_reactor.py
tests/test_parametric_components/test_BlanketFP.py

This PR make the BlanketFP component ignore points if the R coordinate is negative. Thus avoiding potential construction errors from occuring.

Fix overlapping BlanketFP

---

paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
tests/test_parametric_shapes/test_ExtrudeCircleShape.py
tests/test_parametric_shapes/test_ExtrudeMixedShape.py
tests/test_parametric_shapes/test_ExtrudeSplineShape.py
tests/test_parametric_shapes/test_ExtrudeStraightShape.py

PR which fixes the extrusion distance for extruded shapes. Previously, distance was divided by 2 for both extrude_both=True and extrude_both=False. For extrude_both = True, this was fine because the shape was extruded by distance/2 in both directions so the total distance was still equal to distance. However, for extrude_both = False, this resulted in a shape with a total distance of distance / 2. This PR fixes this problem. Also adds tests for each extruded shape to test this feature.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

Fix extrude shapes

---

paramak/parametric_reactors/ball_reactor.py

This small PR fixes #515 by making the offset from plasma of blanket, first wall and rear wall in BallReactor consistent with that of the divertor.

offset from plasma consistent accross components

---

Dockerfile
examples/example_neutronics_simulations/ball_reactor_minimal.py
examples/example_neutronics_simulations/center_column_study_reactor.py
examples/example_neutronics_simulations/center_column_study_reactor_minimal.py
requirements.txt
tests/test_parametric_neutronics/test_NeutronicModelFromReactor.py

This allows the tests to be run from outside docker, including the one neutronics test we have. The neutronics tests been changed a tiny amount (no more material enrichment) so it does not need openmc as described in https://github.com/ukaea/neutronics_material_maker/issues/105

Tiny corrections to allow neutronics testing without openmc

---

tests/test_parametric_components/test_PortCutterCircular.py
tests/test_parametric_components/test_PortCutterRectangular.py

Some really simple creation tests for a couple of components that didn't have any tests.
Interestingly the port cuttr circle works on CQ 2 but fails on CQ master version, at least over here.

added simple creation tests for port cutter circle and rectangle

---

Dockerfile
examples/example_neutronics_simulations/ball_reactor_minimal.py
examples/example_neutronics_simulations/center_column_study_reactor.py
examples/example_neutronics_simulations/center_column_study_reactor_minimal.py
requirements.txt
tests/test_parametric_neutronics/test_NeutronicModelFromReactor.py

This allows the tests to be run from outside docker, including the one neutronics test we have. The neutronics tests been changed a tiny amount (no more material enrichment) so it does not need openmc as described in ukaea/neutronics_material_maker#105

Updating neutronics tests to not need openmc

---

paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/shape.py

PR which adds an extrusion_start_offset parameter to ExtrudeCircleShape so that the extrusion can be offset in the plane perpendicular to the face. This can be done easily for the ExtrudeCircleShape as the workplane can be offset before the face construction at the parametric_shape level. However, for other extruded shapes, the face is already constructed in super().create_solid() and is not easy to offset afterwards at the parametric_shape level, so the offset will have to be implemented in the base Shape class.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …

added extrusion_start_offset to extruded shapes

---

.circleci/config.yml
examples/example_parametric_components/make_all_parametric_components.py
tests/test_parametric_components/test_PortCutterCircular.py

This PR switches the CI back to what it was with a static image for paramak dependencies.
The docker build of the image is done only on branches develop and main. On these branches, if tests pass, the image is pushed to Dockerhub with the tag :latest or :dev. 
Otherwise, only the tests are run with the :dependencies_cq_master image. 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …

Switch back to dependencies image

---

.github/workflows/docker_ci.yml
Dockerfile

This small change to the dockerfile allows the use of another --build-arg in the dockerfile
This build arg controls the number of cores the image is built with. 
Compiling with mutliple cores can speed up the MOAB compile step. 
Using -j is an option but sometimes this can result in other applications closing while the compile takes all of the cpu cores. 
Therefore this setting allows the user or config.yml to specify the number of cores used
Also the documentation at the top of the dockerfile has been updated
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …

allowing user to specify cores

---

paramak/__init__.py
paramak/parametric_components/hollow_cube.py
paramak/parametric_neutronics/neutronics_model_from_reactor.py
paramak/reactor.py
paramak/shape.py
tests/test_Reactor.py
tests/test_parametric_shapes/test_RotateStraightShape.py

This PR moves some of the graveyard creation from Reactor
the largest_dimension has been moved into the attributes of of Shape objects
the 3d hollow cube creation has been moved into a new parametric component called HollowCube.
This is useful as the the Shape objects will need their own Graveyard bounding box if we want to do neutronics simulations on the Shapes.
@billingsley-john  I think the inclusion of a Dagmc Graveyard for Shape objects will now be easier as the useful code is now in more accessable places in the code
This solves #586
Also the largest_dimention attribute can be used to determine 3D and 2D mesh tallies sizes in the neutronics simulations
_Put an `x` in the boxes that …

moved graveyard generation out of reactor

---

paramak/parametric_components/poloidal_field_coil_case_set.py
paramak/parametric_components/poloidal_field_coil_case_set_fc.py
paramak/parametric_components/poloidal_field_coil_set.py
paramak/parametric_components/poloidal_segmenter.py
paramak/parametric_components/port_cutters_rotated.py

Following from from some previous suggestions in the recent catch up I thought I would see if the get_hash call can be removed from all the parametric components. Also nice to reduce the lines of code for a change :-)

removed get_hash

---

paramak/parametric_reactors/ball_reactor.py
paramak/parametric_reactors/submersion_reactor.py

PR which removes number_of_ports as a reactor argument. This was causing competition with port_azimuth_placement_angle and the simplest solution was to remove.

removed number_of_ports as argument

---

paramak/__init__.py
paramak/parametric_components/shell_fs.py
tests/test_parametric_components/test_ShellFS.py

This adds the shell from shape parametric component that we discussed earlier today with @RemDelaporteMathurin and @billingsley-john . 
The final solution is based on a discovery @billingsley-john who found the .shell method. 
The result is a versatile shape with quite a small amount of code.
The shell shape is cut using a WedgeCutterFS() based on the shape passed into the ShellFS()
Unfortunately it fails when trying to offset a certain blanket I'm working on. I believe that is due to the use of splines on the outer part. It works when the blanket is make entirely from straight sections
Also it can fail when the filleted edges make contact each other
TODO
- Docs and images for docs
- add a spline shape to the test
- add a mixed shape to the tests
- add an extrude shape to the tests
- add …

added shellFS component and tests

---

paramak/parametric_neutronics/neutronics_model_from_reactor.py
tests/test_parametric_neutronics/test_NeutronicModelFromReactor.py

This tiny changes allows Reactors to be build from components and shapes manually without having to set the rotation angle.

:tada: not all reactors need rotation angles

---

Dockerfile
tests/test_parametric_neutronics/test_NeutronicModel.py

Just changes the materials so that they work with the nuclear data on the dockerfile

Neutronics simulations for components

---

README.md

This changes the docker hub build status badge. The shields.io one have been replaced with a github actions one

:whale: changed docker badge url

---

tests/test_parametric_neutronics/test_Shape_neutronics.py

This adds a geometry comparison to the test suite. The same source, materials and geometry is simulated using CSG and CAD based geometry. 
The CSG geometry is made using the OpenMC Python API and requires about 40 lines of code.
The CAD geometry is made using the Paramak Python API and requires about 70 lines of code.
The heating tally is obtained with a neutron source (photon transport enabled), 10 batches and 500 particles.
Pytest.approx is then used to check that both simulations return an answer within +/- a relative fraction of 0.001 of each other.
The conversion of the CAD geometry to DAGMC geometry is performed via STL and PyMoab functonality added by @pshriwise 
The CSG cask viewed from above
The CSG cask viewed from the side
The CSG cask converted to VTK and seen in 3D
The CAD …

added csg vs cad simulation test

---

paramak/parametric_neutronics/neutronics_model.py
paramak/shape.py
tests/test_Reactor.py
tests/test_parametric_neutronics/test_NeutronicModel.py
tests/test_parametric_shapes/test_SweepStraightShape.py

Just couldn't resist fixing a few bugs noticed by the PullRequest review, particularly the ones where tests were not actually running due to the duplicate names.
For each commit is in response to a suggestion in https://github.com/ukaea/paramak/pull/639
I have added some text to the suggestions (linking the commit to the suggestion) I am addressing so that these suggestions can be resolved once this PR is merged.
What do people think, is this a reasonable way to go about addressing the comments in the PullRequest review?
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This …

Pull request review fixes

---

.github/workflows/dockerhub-publish-dependencies.yml
paramak/parametric_neutronics/neutronics_model.py

This small change allows users to skip simulations by setting the method to None

Simulate optionally rebuilds model

---

examples/example_neutronics_simulations/shape_with_spectra_cell_tally.py
paramak/parametric_neutronics/neutronics_model.py
tests/test_parametric_neutronics/test_NeutronicModel.py

This adds the ability to tally neutron and photon spectra on the cells.
When defining a model we now have a few cell tallies that are supported (heating, flux, TBR, spectra).
The next tally to add is fast flux which is can be done in a very similar way to spectra but with a two group energy bin and then deletion of the values in the first (thermal) group. Admittedly this is probably not the most efficient way to implement such a tally but good to start somewhere.
Anyway the spectra is by default 709 CCFE energy group so perhaps this should also a user controllable an option in the future.
```
my_model = paramak.NeutronicsModel(
geometry=self.my_shape,
source=self.source,
materials={'center_column_shield_mat': mat},
cell_tallies=['heating', 'flux', 'TBR', 'spectra'],
simulation_batches=2, …
```

Spectra tally on cells

---

paramak/parametric_neutronics/make_faceteted_neutronics_model.py
paramak/shape.py
tests/test_parametric_components/test_CuttingWedge.py

When simulating sector models it is necessary to have reflecting surfaces. This addition facilitates reflecting surfaces being added to the neutronics description and the use of this key within the trelis script.

Adding reflectivity option

---

paramak/parametric_shapes/sweep_circle_shape.py
paramak/shape.py

PR to fix the sweep shapes. Faces placed at path_points were not being translated along the required axis, resulting in faces all being placed at x/y/z=0, at varying offsets. Instead of moveTo(), center() is a better alternative for translating the workplane origin (as suggested by the Cadquery developers).

Fix sweep shapes

---

tests/test_parametric_components/test_CenterColumnShieldCylinder.py
tests/test_parametric_components/test_CenterColumnShieldFlatTopHyperbola.py
tests/test_parametric_components/test_CenterColumnShieldHyperbola.py
tests/test_parametric_components/test_CenterColumnShieldPlasmaHyperbola.py
tests/test_parametric_components/test_CuttingWedgeFS.py
tests/test_parametric_components/test_Plasma.py
tests/test_parametric_components/test_PoloidalFieldCoilCaseSet.py
tests/test_parametric_components/test_PoloidalFieldCoilCaseSetFC.py
tests/test_parametric_components/test_PoloidalFieldCoilSet.py
tests/test_parametric_components/test_ToroidalFieldCoilRectangle.py

PR which re-organises unit tests so that assertions are correctly tested, and we don't get incorrect 'spillover' from previous tests.

Fix assert raises tests

---

.circleci/config.yml
.github/workflows/dockerhub-publish-dependencies.yml
.github/workflows/dockerhub-publish-geometry-dependencies.yml
Dockerfile
DockerfileDependencies
README.md
setup.py

Keen to get this PR merged in as the I am keen to renamed mesh_tally args before anyone starts using them instead of renaming them in a few weeks and cause more trouble for any users. They are a relatively new feature so I think this tiny breaking change will be unnoticed.
- Changes to the NeutronicsModel arguments to make them conform to pep8. 
- mesh_tally_2D is now mesh_tally_2d
- mesh_tally_3D is now mesh_tally_3d
- Minor changes to the dockerfile
- .git has been added to the endings of cloned repos where it was missing. Thanks to @AI-Pranto for spotting that on the workshop repo
- double-down is now using the /embree folder as discussed https://github.com/openmc-dev/openmc/issues/1749

new double down build and mesh tally arg names

---

examples/example_parametric_components/make_all_parametric_components.py
examples/example_parametric_reactors/segmented_blanket_ball_reactor.py
examples/example_parametric_shapes/make_html_diagram_from_stp_file.py
paramak/parametric_components/cutting_wedge_fs.py
paramak/parametric_components/inboard_firstwall_fccs.py
paramak/reactor.py
paramak/shape.py
paramak/utils.py
tests/test_example_shapes.py

This PR adds some helpful functions to the utils
The ```paramak.utils.load_stp_file``` function allows stp files to be loaded and returns the solid and wires.
The ```paramak.utils.export_wire_to_html``` function allows a list of wires to be exported to a html plot.
Reactors can now be viewed from different view_planes
This PR also refactors the various export_html methods in Reactor and Shape classes so that their is less duplication
If this …

Added export html for stp files

---

paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/parametric_shapes/rotate_spline_shape.py
paramak/parametric_shapes/rotate_straight_shape.py
paramak/parametric_shapes/sweep_circle_shape.py
paramak/parametric_shapes/sweep_mixed_shape.py
paramak/parametric_shapes/sweep_spline_shape.py
paramak/parametric_shapes/sweep_straight_shape.py

I am keen to add type hinting to all 12 of the parametric shapes but wanted to check with others if this is a good idea.
So I made a example PR that implements type hinting on one parametric shape and removes the types from the docstring.
If this is acceptable then I can roll this out for all the other 11 shapes
Let me know what you think @RemDelaporteMathurin @billingsley-john

added type hints to args and removed from docstring

---

.github/workflows/docker_ci.yml
.gitignore
README.md
examples/example_parametric_reactors/make_animation.py
examples/example_parametric_shapes/make_CAD_from_points.py
paramak/reactor.py
paramak/shape.py
tests/test_example_reactors.py

This PR updates the export svg methods so that they allow new export options such as view angle and image width.
The animation examples script has also been updated to make use of this improved feature.
Ideally the gif made for the rotation should have their last and first frame blend into each other but I've not quite got the angles x,y,z correct
This makes use of quite a new feature in CQ so the docker image usedin circle ci might need rebuilding for this to pass

added options to svg export

---

paramak/shape.py

This removes the opening of a file and use of exporters.exportShape and replaces it with exporters.export when exporting a stp file as discussed in #82 
The former method is now depreciated.
```angular_tolerance```

updated stp exporter to new cq method

---

paramak/parametric_neutronics/neutronics_model.py

PR which adds an optional openmp_threads argument to .simulate() to control the number of threads OpenMC uses during a simulation.

added openmp threads option

---

.github/workflows/docker_ci.yml
Dockerfile
DockerfileDependencies
examples/example_parametric_reactors/make_animation.py
paramak/neutronics_utils.py
run_tests.sh
setup.py
tests/test_parametric_reactors/test_BallReactor.py

Implemented a few more suggestions from the pullrequest.com review
https://github.com/ukaea/paramak/pull/639
We are down to just 40 remaining suggestions :tada:

Pull request review fixes 0.23
