paramak/parametric_shapes/divertor_block.py, paramak/parametric_shapes/poloidal_field_coil.py, paramak/parametric_shapes/poloidal_field_coil_case.py, paramak/parametric_shapes/tokamak_plasma.py, paramak/rotate_circle_shape.py, paramak/rotate_mixed_shape.py, paramak/rotate_spline_shape.py, paramak/rotate_straight_shape.py, tests/test_RotateCircleShape.py, tests/test_RotateMixedShape.py, tests/test_RotateSplineShape.py
This merges in some parametric shapes, rotate classes and tests to the repo
=> Adding shapes

paramak/__init__.py, paramak/parametric_shapes/__init__.py
This adds init.py files that are needed to install the package with python setup.py
=> added inits for package install

paramak/reactor.py
Adding a missing file, reactor.py
=> added reactor

tests/test_RotateMixedShape.py
This removes a test that use to check the connections were being handled correctly. However the way connections are handled has changed. So test is no longer needed or should be refactored
=> removed incorrect test

tests/local_test_examples.py, tests/test_ExtrudeStraightShape.py, tests/test_Reactor.py, tests/test_RotateStraightShape.py, tests/test_Shape.py, tests/test_examples.py
This PR adds several unit tests for reactor, shape, extrude straight shapes and some tests that work locally but not on the docker image due to graphics problems
=> moved missing test files

tests/test_ExtrudeStraightShape.py, tests/test_RotateStraightShape.py
PR to add the dirty flag tests missing from the straight shape user classes
=> added missing dirty solid flat tests

README.md, examples/make_CAD_from_points.py, examples/make_blanket_from_parameters.py, examples/make_blanket_from_points.py, examples/make_can_reactor_from_parameters.py, examples/make_can_reactor_from_points.py, paramak/extruded_mixed_shape.py, paramak/parametric_shapes/__init__.py, paramak/parametric_shapes/blanket_constant_width.py, paramak/parametric_shapes/center_column_plasma_dependant.py, paramak/parametric_shapes/divertor_block.py, paramak/rotate_mixed_shape.py, paramak/shape.py, tests/test_ExtrudeCircleShape.py, tests/test_ExtrudeMixedShape.py, tests/test_ExtrudeSplineShape.py, tests/test_ExtrudeStraightShape.py, tests/test_Reactor.py, tests/test_RotateMixedShape.py, tests/test_RotateSplineShape.py, tests/test_RotateStraightShape.py, tests/test_Shape.py
This gets the tests working for the recently changed input format. The points now require that the last point is not the same as the first point
=> Getting tests working

paramak/parametric_shapes/center_column_flat_top_hyperbola.py, paramak/parametric_shapes/center_column_hyperbola.py, tests/test_ParametricShapes.py
PR to add testing for parametric shapes. Also removes unnecessary 'last point = first point' from some parametric shapes
=> Add parametric shapes test

README.md
this just changes the circle ci logos, nothing major
=> Updating readme images

paramak/parametric_shapes/blanket_constant_width.py, paramak/parametric_shapes/center_column_cylinder.py, paramak/parametric_shapes/center_column_flat_top_hyperbola.py, paramak/parametric_shapes/center_column_hyperbola.py, paramak/parametric_shapes/center_column_plasma_dependant.py, paramak/parametric_shapes/divertor_block.py, paramak/parametric_shapes/poloidal_field_coil.py, paramak/parametric_shapes/poloidal_field_coil_case.py, paramak/parametric_shapes/tokamak_plasma.py
PR updating parametric shapes. removes unnecessary re-defining of solid getters and setters in the parametric shape classes when they are already inherited from user classes by the super.
Also some minor updates to docstrings and property inheritance.
=> Update parametric shapes

paramak/extruded_spline_shape.py, paramak/extruded_straight_shape.py, paramak/rotate_mixed_shape.py, paramak/rotate_spline_shape.py, paramak/rotate_straight_shape.py
This just removes a few print statements that are no longer needed
=> removed hash status print statement

README.md
adds a few images hosted outside of the github into the readme
=> Extra images

docs/source/index.rst
Adds a few more details to the install
=> added draft conda instructions

paramak/parametric_shapes/__init__.py, paramak/parametric_shapes/inner_tf_coils.py
added new parametric shape describing inner tf coils
=> Add inner tf coils parametric shape

examples/make_animation.py, examples/make_ball_reactor.py, paramak/parametric_shapes/poloidal_field_coil_case.py
this adds the croped use of image magic
=> Cropped animation

docs/source/paramak.parametric_components.rst, examples/make_all_parametric_components.py, paramak/__init__.py, paramak/parametric_components/blanket_constant_thickness_arc_h.py, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/blanket_constant_thickness_fp.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/center_column_cylinder.py, paramak/parametric_components/center_column_flat_top_circular.py, paramak/parametric_components/center_column_flat_top_hyperbola.py, paramak/parametric_components/center_column_hyperbola.py, paramak/parametric_components/center_column_plasma_dependant.py, paramak/parametric_components/divertor_block.py, paramak/parametric_components/inner_tf_coils_circular.py, paramak/parametric_components/inner_tf_coils_flat.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/tokamak_plasma.py, paramak/parametric_components/toroidal_field_coil_rectangle.py, paramak/parametric_shapes/extruded_circle_shape.py, paramak/parametric_shapes/extruded_mixed_shape.py, paramak/parametric_shapes/extruded_spline_shape.py, paramak/parametric_shapes/extruded_straight_shape.py, paramak/parametric_shapes/rotate_circle_shape.py, paramak/parametric_shapes/rotate_mixed_shape.py, paramak/parametric_shapes/rotate_spline_shape.py, paramak/parametric_shapes/rotate_straight_shape.py, paramak/reactor.py, paramak/shape.py, tests/test_ParametricComponents.py, tests/test_examples.py
This adds a new rectangular tf coil to the parametric shapes
some pep 8 formatting was also done
=> New tf outboard coils

paramak/parametric_reactors/ball_reactor.py, tests/test_BallReactor.py, tests/test_ParametricComponents.py, tests/test_SubmersionBallReactor.py
This adds a few unit tests to check creation of a few parametric components and parametric reactors
=> added tests to increase coverage

paramak/reactor.py, tests/test_Reactor.py
This adds a couple of properties to the reactor.
Reactor.stp_filename
Reactor.material_tags
these are both lists of all the material_tags and all the stp_filenames in the reactor
stp_filename is checked when it is inserted to see if there is anything with that name already
=> added stp filename check

docs/source/example_parametric_shapes.rst, docs/source/index.rst
PR which updates parametric_shapes table and adds brief documentation for example_parametric_shapes scripts
=> Update docs images

docs/source/paramak.parametric_components.rst, examples/example_parametric_components/make_all_parametric_components.py, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, tests/test_ParametricComponents.py, tests/test_examples.py
this adds a coat hanger style parametric component to the components
tests and documentation have also been added
=> added image to documentation

paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_rectangle.py
=> fixed typo in docstring

paramak/parametric_components/center_column_circular.py, paramak/parametric_components/center_column_flat_top_circular.py, paramak/parametric_components/poloidal_field_coil_case.py, paramak/parametric_components/poloidal_field_coil_case_fc.py, paramak/parametric_components/tokamak_plasma.py, paramak/parametric_components/toroidal_field_coil_rectangle.py, paramak/reactor.py
Just adding a few details to the docstrings where some details were missing
=> add missing details to doc strings

examples/example_parametric_reactors/make_parametric_ball_reactor.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/submersion_ball_reactor.py, setup.py
This adds .solid to parametric reactors so that the complete reactor be rendered in jupyter notebooks
=> added .solid to reactor classes

.gitignore, docs/source/paramak.parametric_reactors.rst, examples/example_neutronics_simulations/make_unstructured_mesh.py, examples/example_parametric_components/make_plasmas.py, examples/example_parametric_reactors/make_parametric_ball_reactor.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/submersion_ball_reactor.py, paramak/reactor.py, tests/test_BallReactor.py, tests/test_SubmersionBallReactor.py, tests/test_examples.py
Just a small update which gets one of the examples working again (make_plasmas.py) and starts fixing the parametric reactors.
=> Update for new plasma

.github/workflows/python-publish.yml
PR to add github action which automatically updates the paramak python package on pypi when pushes are made to the main branch
=> added action to update pip install from pushes to main branch

paramak/parametric_components/blanket_constant_thickness_fp.py
=> BlanketConstantThicknessFP full coverage fix

docs/source/example_neutronics_simulations.rst, docs/source/example_parametric_reactors.rst, examples/example_neutronics_simulations/make_unstructured_mesh.py, examples/example_neutronics_simulations/parametric_ball_reactor_neutronics_model.py, examples/example_neutronics_simulations/parametric_shape_neutronics_model.py, examples/example_parametric_reactors/make_animation.py, examples/example_parametric_reactors/make_parametric_ball_reactor.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_reactors/ball_reactor.py, paramak/reactor.py, tests/test_BallReactor.py, tests/test_Reactor.py
This PR updates the neutronics examples.
There is now an improved neutronics simulation for parametric shapes and a new example for a parametric reactor
Documentation has also been updated
Reactor materials has been changed to a set to avoid duplication
=> improved examples for neutronics examples

paramak/parametric_shapes/rotate_circle_shape.py, paramak/parametric_shapes/rotate_mixed_shape.py, paramak/parametric_shapes/rotate_spline_shape.py, paramak/parametric_shapes/rotate_straight_shape.py
This PR contains an update to docstrings for some parametric_shapes. The main reason for this PR is to test whether a PR to the develop branch triggers a pip build
=> updated docstrings

paramak/parametric_shapes/extruded_straight_shape.py
PR to test whether the new pip build workflow works. The python-publish.yml file has been updated so that it should only trigger a build on pushes and PRs to the main branch. Before, it was triggering on any PR to any branch
=> updated docstring

paramak/parametric_components/center_column_circular.py, paramak/parametric_components/center_column_cylinder.py, paramak/parametric_components/center_column_flat_top_circular.py, paramak/parametric_components/center_column_flat_top_hyperbola.py, paramak/parametric_components/center_column_hyperbola.py, paramak/parametric_components/center_column_plasma_dependant.py, paramak/parametric_components/divertor_block.py, paramak/parametric_components/inner_tf_coils_circular.py, paramak/parametric_components/inner_tf_coils_flat.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/poloidal_field_coil_case.py, paramak/parametric_components/poloidal_field_coil_case_fc.py, paramak/parametric_components/tokamak_plasma.py, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_rectangle.py
PR which changes the super().__init__ of most parametric_components to use a default_dictionary as described in #110
=> updated super to use default_dict

paramak/parametric_components/blanket_constant_thickness_arc_h.py, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/blanket_constant_thickness_fp.py
PR to adds the hash_value solid construction test and update super().__init__ to use default_dict for blanket components
=> added hash value check and updated super

examples/example_parametric_reactors/make_animation.py, paramak/reactor.py
This PR updates the make_animation script so that it is using the current ball reactor arguments
=> fixed animations

README.md, docs/source/index.rst, paramak/parametric_shapes/extruded_mixed_shape.py, paramak/parametric_shapes/extruded_spline_shape.py, paramak/parametric_shapes/extruded_straight_shape.py, paramak/parametric_shapes/rotate_mixed_shape.py, paramak/parametric_shapes/rotate_spline_shape.py, paramak/parametric_shapes/rotate_straight_shape.py
PR which updates the github README and readthedocs index.rst.
=> Update docs and readme

examples/example_parametric_reactors/make_all_parametric_reactors.py, examples/example_parametric_reactors/make_animation.py
This adds the ballreactor with TF coils to the example parametric reactors so that the SVG image and animation can be created
=> now with tf coils

paramak/parametric_components/divertor_ITER.py
=> Divertors docstring fix

examples/example_parametric_reactors/make_parametric_ball_reactor.py, paramak/__init__.py, paramak/parametric_components/blanket_constant_thickness_arc_h.py, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/blanket_constant_thickness_fp.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/center_column_cylinder.py, paramak/parametric_components/center_column_flat_top_circular.py, paramak/parametric_components/center_column_flat_top_hyperbola.py, paramak/parametric_components/center_column_hyperbola.py, paramak/parametric_components/center_column_plasma_dependant.py, paramak/parametric_components/divertor_block.py, paramak/parametric_components/inner_tf_coils_circular.py, paramak/parametric_components/inner_tf_coils_flat.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/poloidal_field_coil_case.py, paramak/parametric_components/poloidal_field_coil_case_fc.py, paramak/parametric_components/tokamak_plasma.py, paramak/parametric_components/tokamak_plasma_from_points.py, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_rectangle.py, paramak/parametric_reactors/ball_reactor.py, setup.py, tests/test_ParametricComponents.py
This PR allows a plasma to be build from the 4 coordinates (top, botton, inner, outer). The 4 plasma shaping parameters are found from these coordinates and then used to build a regular plasma.
This plasma is needed to help make parametric reactors with a vertical build
=> added draft new plasma

docs/source/paramak.parametric_reactors.rst, examples/example_parametric_reactors/make_all_parametric_reactors.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/submersion_reactor.py, tests/test_SubmersionTokamak.py
This PR makes use of the new union and intersect features in the submersion reactor
This also adds TF coils, PF coils, support legs to the model
Also the reactor now raises and error if the plasma high point is outside of the allowable region
=> Improved sub reactor

docs/source/paramak.parametric_reactors.rst, environment.yml
This tiny PR adds plasma boundaries to the docs
=> added pip package

docs/source/paramak.parametric_components.rst, paramak/parametric_components/blanket_constant_thickness_arc_h.py, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/center_column_cylinder.py, paramak/parametric_components/center_column_flat_top_circular.py, paramak/parametric_components/center_column_flat_top_hyperbola.py, paramak/parametric_components/center_column_hyperbola.py, paramak/parametric_components/center_column_plasma_dependant.py, paramak/parametric_components/inner_tf_coils_circular.py, paramak/parametric_components/inner_tf_coils_flat.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/poloidal_field_coil_case.py, paramak/parametric_components/poloidal_field_coil_case_fc.py, paramak/parametric_components/tokamak_plasma_from_points.py, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_rectangle.py
PR which adds some **kwargs for the parametric_shapes to the docs and reformats them to google-style
=> Update docs with kwargs

examples/example_parametric_components/make_plasmas.py
PR which plots basic plasmas on the left and plasmaboundaries plasmas on the right
=> basic plasma shapes now plotted on left

.circleci/config.yml, docs/source/index.rst, paramak/__init__.py, paramak/parametric_components/toroidal_field_coil_princeton_d.py, paramak/parametric_components/toroidal_field_coil_triple_arc.py, tests/test_ParametricComponents.py
This updates the circle ci to use the latest docker image and adds a few lines to the docs on the use of docker images
=> added new dockerimage for ci and to docs

paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/single_null_ball_reactor.py, paramak/parametric_reactors/single_null_submersion_reactor.py, paramak/parametric_reactors/submersion_reactor.py
PR which moves the rotation_angle == 360 check into a method
=> moved rotation_angle check into method

paramak/reactor.py, paramak/shape.py
PR which converts the docstrings in shape.py and reactor.py to google style and documents the class properties correctly
=> updated docstring format

tests/test_RotateStraightShape.py, tests/test_utils.py
Adds tests for boolean cuts and find_center_point_of_circle function to increase code coverage.
=> added test for boolean cut and util function

tests/test_Shape.py
PR to add more tests which test methods in the Shape class. Many of the if/else statements raising ValueErrors were missing from the test suite.
=> added tests to increase codecov

paramak/parametric_components/center_column_hyperbola.py, paramak/parametric_components/divertor_ITER.py, paramak/parametric_components/inner_tf_coils_circular.py, paramak/parametric_components/inner_tf_coils_flat.py, paramak/parametric_components/tokamak_plasma_from_points.py, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_princeton_d.py, paramak/parametric_components/toroidal_field_coil_rectangle.py, paramak/parametric_components/toroidal_field_coil_triple_arc.py, paramak/shape.py
Like #254, azimuth_placement_angle getter/setter pair can be removed from parametric_component classes and inherited directly from shape, and find_azimuth_placement_angle can be called directly.
=> Parametric components angle

.github/pull_request_template.md
Adds 'Code refactoring' as an option under Types of changes in the PR template.
=> add code refactoring to template

.github/workflows/python-publish.yml, AUTHORS.md, bld.bat, build.sh, docs/source/conf.py, examples/example_parametric_components/make_plasmas.py, meta.yaml, paramak/shape.py, setup.py
Adding files needed for a conda install
Also removed names (Jon and John)  from setup.py and config.yml and replaced with the whole Team to include others who have contributed (as mentioned in the Authors.md), also updated the authors.md file to include recent additions
=> Adding conda install2

docs/source/index.rst
This PR adds a link to the recently approved presentation into the documentation as mention in #278
- x ] I have added necessary documentation (if appropriate)
=> added presentation link

paramak/shape.py
Removes unnecessary checks in the azimuth_placement_angle setter
=> removed unnecessary checks

examples/example_parametric_components/make_magnet_set.py
This PR will add an example for a complete magnet collection, TF, PF and some casing. While getting started on the feature I noticed a few more mini features are needed to make this task easier. This PR is therefore a draft while the other features are added (see Todo list lower down and issues #274 #273 )
ToDo
add parametric component that allows several pf coils to be added at once
add connection points to tf coil #274 , the add inboard tf legs using ExtrudeStraightShape()
allow user specified rotation angles for TF coils #273 
add a triangle shape for the inner and outer tf connection
=> Adding magnet set example

tests/test_ParametricComponents.py, tests/test_RotateSplineShape.py
Adding a test to check color is being handled correctly
=> Adding tests for color property

paramak/parametric_components/toroidal_field_coil_princeton_d.py, tests/test_ParametricComponents.py
This PR solves #274 by adding a new attribute to the `ToroidalFieldCoilPrincetonD()` class which contains 4 points coordinates
Usage:
```python
import paramak
my_magnet = paramak.ToroidalFieldCoilPrincetonD(R1=0.29, R2=0.91, thickness=0.05, distance=0.05, number_of_coils=1)
my_magnet.export_stp('princeton.stp')
my_leg = paramak.ExtrudeStraightShape(points=my_magnet.inner_leg_connection_points, distance=0.05)
my_leg.export_stp('leg.stp')
```
=> Connection points for PrincetonD magnet

examples/example_parametric_components/make_magnet_set.py, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/blanket_fp.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/center_column_cylinder.py, paramak/parametric_components/center_column_flat_top_circular.py, paramak/parametric_components/center_column_flat_top_hyperbola.py, paramak/parametric_components/center_column_hyperbola.py, paramak/parametric_components/divertor_ITER.py, paramak/parametric_components/inner_tf_coils_flat.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/poloidal_field_coil_case.py, paramak/parametric_components/poloidal_field_coil_case_fc.py, paramak/parametric_components/poloidal_field_coil_case_set.py, paramak/parametric_components/tokamak_plasma.py, paramak/parametric_components/tokamak_plasma_plasmaboundaries.py, paramak/parametric_components/toroidal_field_coil_princeton_d.py, paramak/parametric_components/toroidal_field_coil_rectangle.py, paramak/parametric_shapes/extruded_circle_shape.py, paramak/parametric_shapes/extruded_mixed_shape.py, paramak/parametric_shapes/extruded_spline_shape.py, paramak/parametric_shapes/extruded_straight_shape.py, paramak/parametric_shapes/rotate_circle_shape.py, paramak/parametric_shapes/rotate_mixed_shape.py, paramak/parametric_shapes/rotate_spline_shape.py, paramak/reactor.py, paramak/shape.py, tests/test_ParametricComponents.py
This PR improves the magnet example a little more by making use of the new connectors on the TF coils
Also tidied up the code in a few places (removed print statements and made a few lines shorter to abide by the 80 char limit)
ToDo
- Tests
- Docs
In other PRs 
- add ability for a user to specify the azimuth_placement_angle for the ToroidalFieldCoilPrincetonD and InnerTfCoilsFlat
- add ability for a user to specify the rotation angle for extruded shapes and create a corresponding cutting slice
=> Improving magnet example

paramak/__init__.py, paramak/parametric_components/blanket_fp.py, paramak/parametric_components/toroidal_field_coil_princeton_d.py, paramak/parametric_reactors/center_column_study_reactor.py, paramak/parametric_reactors/single_null_submersion_reactor.py, paramak/parametric_reactors/submersion_reactor.py, tests/test_CenterColumnStudyReactor.py, tests/test_ParametricComponents.py, tests/test_RotateSplineShape.py
As discussed in #284 there is a need for a reactor that has the most simple outboard blanket but a more complex center column for carrying out parameter studies on the center column shielding
This PR is a working progress as one of the arguments is not working quite yet.
ToDo
- The argument plasma_gap_vertical_thickness is not shifting the blanket height and this will require a little tinkering to fix
- Documentation (including diagrams with …
=> added first draft of center column study reactor

docs/source/example_parametric_components.rst
Just updating an image to include all the current parametric components
=> updated image

paramak/parametric_components/blanket_fp.py, tests/test_ParametricComponents.py
This PR includes a new feature for the `BlanketFP` which allows the user to specify variable thickness (resp. offset) from a list of angles and a list of values. 
The actual thickness (resp. offset) will be a linear interpolation of the values provided with respect to the angles provided. If no angles are provided (ie, only one list is passed) then the values will be interpolated on angles equally spaced between `start_angle `and `stop_angle`
This doesn't change the old behaviour of passing a tuple of 2 thicknesses (or offsets).
Usage
```python
import paramak
list_of_angles = (0, 50, 100)
list_of_thicknesses = (10, 200, 100)
shape = paramak.BlanketFP(thickness=[list_of_angles, list_of_thicknesses], start_angle=0, stop_angle=100, rotation_angle=180)
shape = …
```
=> BlanketFP variable thickness and offset from lists of angle and values

paramak/parametric_components/inner_tf_coils_circular.py, paramak/parametric_components/inner_tf_coils_flat.py, tests/test_ParametricComponents.py
PR which checks gap_size is not too large for inner tf coils.
=> added gap_size check

docs/source/paramak.parametric_components.rst, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, tests/test_ParametricComponents.py
This adds an inboard leg to the ToroidalFieldCoilCoatHanger parametric shape and updates the docs to show the parameters for the ToroidalFieldCoilCoatHanger shape
This is part of a series of improvements to the documentation of the tf coils
=> Adding tf coat hanger inner leg

examples/example_neutronics_simulations/central_column_shield_study.py
An example parameter study of a central column shielding simulation
ToDo
Addition of OpenMC model
Plots of the data
=> Param study central column

paramak/__init__.py, paramak/parametric_components/cutting_wedge.py, paramak/parametric_components/cutting_wedge_fs.py
PR which adds two cutting wedge parametric shapes.
CuttingWedge where height, radius and rotation_angle can be defined.
CuttingWedgeFS which takes a shape as an argument and uses the rotation_angle specified in the shape (this may need to be changed)
=> added cutting wedge components

paramak/parametric_components/cutting_wedge_fs.py, tests/test_ParametricComponents.py
Adds a fuzzy test to the test suite for the new cutter parametric shape
=> added fuzzy test

docs/source/paramak.parametric_components.rst, paramak/parametric_components/cutting_wedge.py, paramak/parametric_components/cutting_wedge_fs.py
Adds documentation for the recently added CutterWedge and cutterWedgeFS
=> added doc strings and images to read the docs

docs/source/paramak.parametric_components.rst
This just adds a couple of images to the docs for the Plasma() and PlasmaFromPoints()
=> added images for plasma

docs/source/paramak.parametric_components.rst
Just adds a few more images from mathcha.io into the docs. These look like they have been in mathcha for a while but we just forgot to add them to readthedocs. Happy to see good work not going to waste :-)
=> added pf coil and pf coil case images

docs/source/paramak.parametric_components.rst, paramak/parametric_components/toroidal_field_coil_triple_arc.py
This adds an optional inner leg to the triple arc style magnet just like the other tf magnets
=> Adding legs to tf triple arc

docs/source/paramak.parametric_components.rst, paramak/parametric_components/toroidal_field_coil_triple_arc.py
Just changes one of the arguments in the triple arc tf coil (height) which was actually 2 * height .
Also adds some documentation images for the triple arc tf coil
=> changed h arg and added images to docs

paramak/parametric_components/toroidal_field_coil_triple_arc.py
=> Automated autopep8 fixes

.gitignore, docs/source/paramak.parametric_components.rst, tests/test_PortCutterRotated.py
Just a small correction to the port cutter docs where a file name had been incorrectly entered and was causing the docs to build incorrectly
Also added some tests that were missing from the previous PR
=> fixed filename in docs

docs/source/paramak.parametric_components.rst, paramak/__init__.py, paramak/parametric_components/poloidal_field_coil_fp.py, tests/test_parametric_components/test_PoloidalFieldCoilFP.py, tests/test_parametric_components/test_PortCutterRotated.py
adds a new component to make building pf coils a little quicker, just two corner points are needed
=> Adding pf coils from corners

paramak/parametric_components/toroidal_field_coil_princeton_d.py, paramak/parametric_components/toroidal_field_coil_triple_arc.py, paramak/parametric_shapes/extruded_circle_shape.py, paramak/parametric_shapes/extruded_mixed_shape.py, paramak/parametric_shapes/extruded_spline_shape.py, paramak/parametric_shapes/extruded_straight_shape.py, paramak/parametric_shapes/rotate_circle_shape.py, paramak/parametric_shapes/rotate_mixed_shape.py, paramak/parametric_shapes/rotate_spline_shape.py, paramak/parametric_shapes/rotate_straight_shape.py, paramak/shape.py
This PR aims at refactoring the parametric shapes by avoiding code repetition with solid getters & setters.
- refactoring
- In TripleArc and PrincetonD magnets, the way of including the inner leg was replaced by conditionnal construction of points reducing the code repetition
=> Parametric shapes refactoring

Dockerfile
Updating the dockerfile trying to make it more compact
the last dockerfile was too large for github actions and error messages "run out of memory" were reported by the git actions
=> using minconda for dockerfile

Dockerfile
adding the readme.md as it is needed by the setup.py
=> updating dockerfile

docs/source/index.rst, docs/source/paramak.core_modules.rst, docs/source/paramak.parametric_shapes.rst, paramak/parametric_shapes/extruded_circle_shape.py, paramak/parametric_shapes/extruded_mixed_shape.py, paramak/parametric_shapes/extruded_spline_shape.py, paramak/parametric_shapes/extruded_straight_shape.py, paramak/parametric_shapes/rotate_circle_shape.py, paramak/parametric_shapes/rotate_mixed_shape.py, paramak/parametric_shapes/rotate_spline_shape.py, paramak/parametric_shapes/rotate_straight_shape.py
Just fixing some typos in the docs and some pep8 line length
=> Fixing docs

paramak/parametric_reactors/ball_reactor.py
Adding getter and setter for ball reactor attributes pf_coil_radial_thickness and pf_coil_vertical_thickness to address issue #363 
I only added getters and setters for pf_coil_radial_thickness and pf_coil_vertical_thickness as outlined in the issue, but if you want any of the …
=> Issue #363

docs/source/index.rst, paramak/parametric_components/poloidal_field_coil_set.py
Small fix for error in docs as reported by #370
=> fixed table and coil args

docs/source/paramak.parametric_reactors.rst, docs/source/tests.rst, examples/example_neutronics_simulations/parametric_ball_reactor_neutronics_model.py, examples/example_neutronics_simulations/parametric_shape_neutronics_model.py, examples/example_parametric_components/make_demo_style_blankets.py, examples/example_parametric_components/make_firstwall_for_neutron_wall_loading.py, examples/example_parametric_components/make_plasmas.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/center_column_study_reactor.py, paramak/parametric_reactors/single_null_submersion_reactor.py, paramak/parametric_reactors/submersion_reactor.py, paramak/utils.py
=> Fixing docs2

paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/center_column_study_reactor.py, paramak/parametric_reactors/single_null_ball_reactor.py, paramak/parametric_reactors/single_null_submersion_reactor.py, paramak/parametric_reactors/submersion_reactor.py, paramak/reactor.py
This PR makes use of the improved TF coils that are cut to the correct rotation angle.
Due to #382 we are able to remove a few lines from the reactors
I also started implementing the create_solids methods like we have lower down in the code. The geometry is still created on reactor initialization for now. But this has the advantage that the single null reactors can call create_solid and overwrite the make_divertor method
=> Simplify reactor

paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/submersion_reactor.py, paramak/shape.py, tests/test_parametric_reactors/test_BallReactor.py, tests/test_parametric_reactors/test_CenterColumnStudyReactor.py, tests/test_parametric_reactors/test_SubmersionTokamak.py
Adds tests to check the reactor rotation is working correctly.
Makes reactors with 90 and 180 degree rotation and checks the volume is roughly doulbe in the 180 case
Also a small bug fix. Compound volumes could not be found for pf coil sets as they are a compound instead of a reagular cq shape. The ability to get the volume of these special components has been added
=> Adding tests for reactor rotation

examples/example_parametric_shapes/make_CAD_from_points.py, paramak/parametric_shapes/sweep_circle_shape.py, paramak/shape.py, tests/test_SweepCircleShape.py
PR which specifies shape.points = shape.path_points for SweepCircleShape, which allows a graph of the spline path to be exported using export_html
=> added points = path_points

paramak/shape.py
This PR proposes small refactoring changes in Shape() as well as pep8 linting.
Garanteed zero pep8 error ✔️ 
=> Refactoring of Shape() + pep8

paramak/parametric_reactors/ball_reactor.py, paramak/reactor.py
Some small changes that accidentally got included in the neutronics branch. These are useful for neutronics but should be separate. 
- This adds the option of including the graveyard or not when creating neutronics descriptions. 
- Also allows the plasma to be removed from the list of material tags associated with a reactor
- Also adds some material tags to the ball reactor where material tags were missing
=> small changes to Reactors help with neutronics analysis

docs/source/paramak.parametric_components.rst
A couple of changes to the images in the docs
Slighlt smaller BlanketCutters so that they fit side by side and changed the plasmaboundary image to the below image
=> shrunk images to fit in line

paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_rectangle.py, paramak/parametric_shapes/extruded_circle_shape.py, paramak/parametric_shapes/extruded_mixed_shape.py, paramak/shape.py, paramak/utils.py
PR which fixes automatic wedge cutter. shape.cut is no longer utilized so that 'old' cutting wedges do not remain as rotation_angle is updated.
=> Fix wedge cutter

docs/source/index.rst
Minor update to the index page of readthedocs.
Now includes images of the sweep shapes in the table and images of the components.
=> updated table

.circleci/config.yml
This is WIP. I thought the CI would be triggered from my fork. moving to local branch
=> WIP: Tests workflow

tests/test_parametric_components/test_ToroidalFieldCoilCoatHanger.py
Added area test for ToroidalFieldCoilCoatHanger parametric shape
=> added area test

tests/test_parametric_components/test_BlanketConstantThicknessArcH.py, tests/test_parametric_components/test_BlanketConstantThicknessArcV.py, tests/test_parametric_components/test_BlanketFP.py, tests/test_parametric_components/test_CenterColumnShieldCircular.py, tests/test_parametric_components/test_CenterColumnShieldCylinder.py, tests/test_parametric_components/test_CenterColumnShieldFlatTopCircular.py, tests/test_parametric_components/test_CenterColumnShieldFlatTopHyperbola.py, tests/test_parametric_components/test_CenterColumnShieldHyperbola.py, tests/test_parametric_components/test_CenterColumnShieldPlasmaHyperbola.py, tests/test_parametric_components/test_DivertorITER.py, tests/test_parametric_components/test_DivertorITERNoDome.py, tests/test_parametric_components/test_Plasma.py, tests/test_parametric_components/test_PoloidalFieldCoil.py, tests/test_parametric_components/test_PoloidalFieldCoilCase.py, tests/test_parametric_components/test_PoloidalFieldCoilCaseFC.py, tests/test_parametric_components/test_PoloidalFieldCoilCaseSet.py, tests/test_parametric_components/test_PoloidalFieldCoilCaseSetFC.py, tests/test_parametric_components/test_PoloidalFieldCoilSet.py
PR to add area and volume tests to the majority of parametric components. This allows the testing of these shapes to be much more thorough as it closely tests shape attributes, rather than simply testing whether a solid has been constructed or not (in some cases).
=> added area and volume tests

examples/example_neutronics_simulations/make_faceteted_neutronics_model.py
Trelis was not liking the use of docstring """ quotes so the make_faceteted_geometry.py script has been updated to use # instead
=> replaced docstrings with #

docs/source/paramak.parametric_components.rst, paramak/parametric_components/toroidal_field_coil_coat_hanger.py
Updates labelled images for tf coils and renames tf coil argument from vertical_start_point to vertical_mid_point to be consistent with other classes, and more intuitive.
=> renamed argument

paramak/parametric_shapes/sweep_circle_shape.py, paramak/parametric_shapes/sweep_mixed_shape.py, paramak/parametric_shapes/sweep_spline_shape.py, paramak/parametric_shapes/sweep_straight_shape.py, paramak/shape.py, tests/test_parametric_shapes/test_SweepCircleShape.py, tests/test_parametric_shapes/test_SweepMixedShape.py, tests/test_parametric_shapes/test_SweepSplineShape.py, tests/test_parametric_shapes/test_SweepStraightShape.py
This is the first attempt at adding a conditional flag to swept shapes which determines whether the shape attempts to keep the cross-sectional area of the shape constant in the plane of the end faces. This is useful for constructing things like coolant channels with an approximately constant cross-sectional area.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
=> attempted adding in conditional flag

paramak/parametric_reactors/ball_reactor.py, paramak/utils.py
Merges new methodology for adding a reactor hash value.
=> Add reactor hash 2

paramak/parametric_components/poloidal_field_coil_set.py, paramak/parametric_reactors/ball_reactor.py
PR which incorporates the hash_value conditional recalculation of solids into the shapes_and_components getter and setter
=> added shapes_and_components getter setter

README.md, docs/source/index.rst
Updating the image of the parameteric components to include a few that were missed from the previous image
=> removed old image of components

paramak/parametric_reactors/single_null_submersion_reactor.py, paramak/parametric_reactors/submersion_reactor.py, paramak/utils.py, tests/test_parametric_reactors/test_BallReactor.py, tests/test_parametric_reactors/test_SingleNullBallReactor.py, tests/test_parametric_reactors/test_SingleNullSubmersionTokamak.py, tests/test_parametric_reactors/test_SubmersionTokamak.py
PR which implements the conditional reconstruction of reactor components with a hash value to the other parametric reactors
=> Add sub reactor hash

paramak/utils.py
PR to update which class parameters are used to calculate the reactor hash value
=> updated keys to ignore in hash value

tests/test_parametric_shapes/test_RotateSplineShape.py
Having this failing test unable to compute code coverage for every PR. This PR removes it and refers to the repo issues where MWEs reproduce the bugs.
=> Remove failing volume test

examples/example_parametric_components/make_all_parametric_components.py, tests/test_parametric_components/test_ToroidalFieldCoilCoatHanger.py
Tests were failing due to a variable name that had changed. This PR fixes it.
=> renamed vertical_start_point to vertical_mid_point

tests/test_parametric_components/test_CenterColumnShieldCircular.py
This PR fixes a failing test in test_CenterColumnShieldCircular.py.
=> Fix center column shield circular faces test

docs/source/paramak.parametric_shapes.rst
Small PR to update one image link for readthedocs documentation.
=> updated ExtrudeSplineShape image

paramak/parametric_reactors/submersion_reactor.py
This is another go at  #476 which got a bit messed up
The BallReactor and Submersion reactor have the same rectangular magnets and from a distance look very similar. To highlight the different magnet sets available this PR makes use of the recently fixed #474 coat hanger TF coils.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …
=> switched magnets

paramak/parametric_reactors/submersion_reactor.py
PR to add pf coil radial and vertical thicknesses getters and setters to submersion_reactor to make SubmersionTokamak consistent with BallReactor.
=> added thicknesses getters and setters

paramak/parametric_components/poloidal_field_coil_case_set.py, paramak/parametric_components/poloidal_field_coil_case_set_fc.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/segmented_blanket_ball_reactor.py, paramak/parametric_reactors/submersion_reactor.py, tests/test_parametric_components/test_PoloidalFieldCoilCaseSet.py, tests/test_parametric_components/test_PoloidalFieldCoilCaseSetFC.py, tests/test_parametric_reactors/test_BallReactor.py, tests/test_parametric_reactors/test_SingleNullBallReactor.py, tests/test_parametric_reactors/test_SingleNullSubmersionTokamak.py, tests/test_parametric_reactors/test_SubmersionTokamak.py
This PR adds pf coil cases to the submersion and ball reactor
Case thickness can be controlled with a single number or with a list of numbers
The list allows one to have different size cases for each pf coil, even 0 size cases are allowed
```pf_coil_case_thickness=[40, 50, 1, 10],``` 
```pf_coil_case_thickness=[10,10,10,0, 10],```
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …
=> Adding casing to reactors

paramak/parametric_components/toroidal_field_coil_princeton_d.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/center_column_study_reactor.py, paramak/parametric_reactors/submersion_reactor.py, paramak/reactor.py, paramak/shape.py, paramak/utils.py, tests/test_parametric_reactors/test_CenterColumnStudyReactor.py
For some complex components (with equation solving or optimisers), the `find_points()` method can be very expensive computationnally. This is the case for `ToroidalFieldCoilPrincetonD`, `BlanketFP` and shapes using the points attributes of these shapes.
This same computational issue for `create_solid` has been solved by checking if the instance parameters have changed and running `create_solid` only if they have changed.
This PR proposes to do the same for `find_points`. Therefore another hash value named specific to `find_points `has been added to `Shape()`.
The computational time saved can be estimated with:
```python
import paramak
import time
t = time.time()
magnet = paramak.ToroidalFieldCoilPrincetonD(100, 200, 10, 10, 1)
for i in range(10):
magnet.inner_points
elapsed = time.time() …
```
=> Add points hash value

README.md, docs/source/index.rst, docs/source/paramak.parametric_reactors.rst
Making use of the new reactor examples to generate a new batch of reactor images across the docs and readme
- [c] Documentation Update (if none of the other choices apply)
=> updated reactor images

.github/workflows/dockerhub-publish-dev.yml, .github/workflows/dockerhub-publish-stable.yml, .github/workflows/python-publish.yml, Dockerfile
Just a little update to the dockerfile that was not building
=> added update to find package

Dockerfile
Trying to decrease the docker image size a little more to avoid running out of space
=> added apt clean to free space

Dockerfile
Shrinking the dockerfile a little more using conda clean and triggering github action rebuild
=> added conda clean

paramak/parametric_components/poloidal_segmenter.py
Tiny refactoring of the part of the class that checks if the line extends past 0
=> refactored zero line check

docs/source/example_parametric_components.rst, examples/example_parametric_components/make_vacuum_vessel_with_ports.py, tests/test_example_components.py
Adding a quick example vacuum vessel to put those nice port cutters to use. Came across a small bug / feature while doing this #493 
=> Adding vacuum vessel with port cutters example

tests/test_parametric_components/test_PoloidalFieldCoilCaseSet.py
This PR is a sub PR of #507 and fixes the failing test for PoloidalFieldCoilCaseSet
=> Fix poloidal field coil case set cq master

docs/source/example_parametric_components.rst, examples/example_parametric_components/make_magnet_set.py, paramak/parametric_components/coolant_channel_ring_curved.py, paramak/parametric_components/coolant_channel_ring_straight.py, paramak/utils.py
This adds docs for the magnet set example
Also fixed a few docstring errors that I noticed while building the docs
=> added docs for magnet set example

docs/source/paramak.parametric_reactors.rst, examples/example_parametric_reactors/ball_reactor.py, examples/example_parametric_reactors/ball_reactor_single_null.py, examples/example_parametric_reactors/center_column_study_reactor.py, examples/example_parametric_reactors/make_all_reactors.py, examples/example_parametric_reactors/segmented_blanket_ball_reactor.py, examples/example_parametric_reactors/submersion_reactor.py, examples/example_parametric_reactors/submersion_reactor_single_null.py
This updates the reactor examples to include an svg export and adds a new ballreactor image to the docs.
I should update the submersion reactor as well but that model has a small issue at the moment #511 
=> added svg export

docs/source/paramak.parametric_reactors.rst
Adds a labeled image of the ball reactor with segmented blankets to the docs
=> added_segmented_reactor_docs

paramak/parametric_components/tokamak_plasma.py, paramak/parametric_components/tokamak_plasma_from_points.py, paramak/parametric_components/tokamak_plasma_plasmaboundaries.py, tests/test_parametric_components/test_Plasma.py
This PR is an attempt at fixing #389 and includes refactoring of the plasma shapes
=> Better plasmaboundaries

.circleci/config.yml, Dockerfile, paramak/parametric_reactors/single_null_ball_reactor.py
This updates the circle ci scripts so that they now build the docker image then test the docker image.
This is a really nice upgrade compared to the current situation where we pull a static image and run the tests on that.
Remi was the master mind for this effort
The docker image also allows users to build it with options 
- starting to add neutronics support, including pymoab or not which allows h5 file exports
- with cadquery master branch for the latest release (default)
In the future this could allow us to add other neutronics tools and then run neutronics in the CI
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …
=> Rem attempt build in circle ci

examples/example_parametric_components/make_demo_style_blankets.py, examples/example_parametric_components/make_firstwall_for_neutron_wall_loading.py, examples/example_parametric_reactors/ball_reactor.py, examples/example_parametric_reactors/ball_reactor_single_null.py, examples/example_parametric_reactors/submersion_reactor_single_null.py, examples/example_parametric_shapes/make_blanket_from_parameters.py, examples/example_parametric_shapes/make_blanket_from_points.py, tests/test_example_components.py, tests/test_example_reactors.py, tests/test_example_shapes.py
This PR changes tthe testing of the examples. They are now imported as suggested in #536
=> Importing examples tests

docs/source/paramak.parametric_reactors.rst
Updating the image to include the pf coil cases
=> removed old image

examples/example_parametric_components/make_all_parametric_components.py, tests/test_parametric_components/test_PortCutterCircular.py
This PR removes failing tests related to issue #548 until it is fixed (perhaps by #539 ?).
=> Remove failing test

Dockerfile
This simplifies the docker image a little.
it combines the two of the if statements into one if statement.
This can be done as the arguments have also changed from "release" to "2" and then the argument can be used to select the version of cad query directly
=> removed one if statement

examples/example_parametric_components/make_all_parametric_components.py, examples/example_parametric_shapes/make_CAD_from_points.py, examples/example_parametric_shapes/make_blanket_from_parameters.py, examples/example_parametric_shapes/make_blanket_from_points.py, examples/example_parametric_shapes/make_can_reactor_from_parameters.py, examples/example_parametric_shapes/make_can_reactor_from_points.py
Just a few tiny changes to the examples to try to make them neater. Nothing important here
=> neater examples

.circleci/config.yml
@Shimwell this may fix the warning that we have in CircleCI
=> Fix security warning in CircleCI

.circleci/config.yml
This PR removes the push builds until a proper solution is found.
=> Comment out push in ci

.github/workflows/dockerhub-publish-dev-cd-master.yml, .github/workflows/dockerhub-publish-dev.yml, .github/workflows/dockerhub-publish-stable.yml
This PR update the github actions yml files so that the docker images contain neutronics (moab), cadquery master and are built with two cores.
The actions have also be enabled again
The is a temporary fix to get dockerhub images uploaded without doing it via circle ci 
=> updated github actions docker building ymls

.circleci/config.yml, .github/workflows/docker_ci.yml, Dockerfile, run_tests.sh
This changes the tests slightly to allow the github actions to run the tests in a more optimal order and includes neutronics tests in the circle ci which is great for coverage
=> Updated test to include neutronics

.github/workflows/docker_ci.yml
This PR just changes the working directory before running the tests in github actions. This is needed as a run_tests.sh script is now being used.
=> changing dir for docker workdir compatabilitiy

examples/example_parametric_reactors/htc_reactor.py, tests/test_example_reactors.py
Removes a duplicate component in the htc reactor example and adds tests for the htc reactor example
=> Tidy spar example

examples/example_neutronics_simulations/center_column_study_reactor.py, examples/example_neutronics_simulations/center_column_study_reactor_minimal.py, examples/example_neutronics_simulations/submersion_reactor.py, examples/example_neutronics_simulations/submersion_reactor_minimal.py
PR to fix the example_neutronics_simulations scripts. 
Scripts now using elongation and triangularity rather than plasma high_point.
=> Fix neutronics examples

.circleci/config.yml, paramak/__init__.py, paramak/neutronics_utils.py, paramak/reactor.py, run_tests.sh, tests/test_Reactor.py, tests/test_neutronics_utils.py, tests/test_parametric_neutronics/test_Reactor_neutronics.py
This is the first stage of getting neutronics testing into the CI and relates to part of issue #584 
I am keen to see if the mb object can be passed to a function and returned in this manner
=> moved moab core opperations to function for use elsewhere

.circleci/config.yml
This PR adds the forgotten `--cov-apend` to the CircleCI config file.
=> added --cov-apend to utils tests

paramak/parametric_neutronics/neutronics_model_from_reactor.py
This removes the hard coded parametric plasma source from the neutronics model and allows any source to be entered
=> now allowing source as neutronics input

paramak/neutronics_utils.py, paramak/parametric_components/blanket_poloidal_segment.py, paramak/parametric_components/poloidal_field_coil_case_set_fc.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/center_column_study_reactor.py, paramak/parametric_reactors/submersion_reactor.py, paramak/reactor.py, paramak/shape.py
Implements a few suggestions for code-inspector. Nothing major just a few cases where we didn't add the attribute to the init, a few unnecessary else statements and other minor improvements.
As a result of #593 the code-inspector score increase from 58 (red) to 63 (orange) and I am hoping this PR might bring the score up perhaps a little bit more.
If this is a relatively large or complex change, kick off the discussion by explaining why you …
=> implemented suggestions from code-inspector

examples/example_neutronics_simulations/ball_reactor.py
adds a missing source argument to one of the examples
=> added mssing arg

tests/test_parametric_neutronics/test_NeutronicModelFromReactor.py
This PR adds tests for the production of 2D mesh tally images which should add to the coverage for the neutronics class (which is a bit low currently)
=> More neutronics tests

paramak/parametric_components/coolant_channel_ring_curved.py, paramak/parametric_components/coolant_channel_ring_straight.py, tests/test_parametric_components/test_CoolantChannelRingCurved.py, tests/test_parametric_components/test_CoolantChannelRingStraight.py
New version of #588.
PR which adds a start angle to CoolantChannelRing* parametric components.
=> Add start angle offset

.circleci/config.yml
added a small comment asking for specific helpt
=> added pullrequest comment

paramak/parametric_components/port_cutters_circular.py, paramak/parametric_components/port_cutters_rectangular.py
PR which replaces the z_pos argument with a center_point argument, allowing the port cutter face position to be specified in two dimensions.
=> Add center point

paramak/parametric_components/port_cutters_rectangular.py, paramak/parametric_reactors/ball_reactor.py, paramak/utils.py
PR which adds automatic port cutting to the ball_reactor.
perform_port_cutting added as a utility function which is used by the ball_reactor if all required arguments have been passed.
=> Add ports to ball reactor

paramak/parametric_components/port_cutters_rectangular.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_shapes/extruded_mixed_shape.py
PR which changes the point at which the filleting is performed for the port cutters. Filleting is required before the port cutters are placed at each azimuth placement angle to only fillet the desired edges.
=> Change port architecture

docs/source/paramak.parametric_components.rst, examples/example_parametric_components/make_all_parametric_components.py, paramak/__init__.py, paramak/parametric_components/rotated_isosceles_triangle.py, paramak/parametric_components/rotated_trapezoid.py, tests/test_parametric_components/test_RotatedIsoscelesTriangle.py, tests/test_parametric_components/test_RotatedTrapezoid.py
Adding another triangle shape. This time a simple isosceles triangle with a base and height.
=> Added an isosceles triangle parametric shape

docs/source/paramak.parametric_components.rst
PR to update the image for the princeton D tf coil
=> added new tf princeton d coil image

paramak/reactor.py
Just removes a print statement that was in the code as a diagnostic
=> removed printing of largest dim

README.md, docs/source/index.rst
Adds a few links to the PullRequest review pdf doc and PR to the Readme and index page on the docs. 
Also removed the white space under the video
=> Adding review to docs

paramak/parametric_neutronics/neutronics_model.py, tests/test_parametric_neutronics/test_NeutronicModel.py
This allows users to set the batch to things like 1e4 which is a float
=> allowing floats and ints for batches and particles

paramak/parametric_components/blanket_constant_thickness_arc_h.py, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/blanket_cutter_parallels.py, paramak/parametric_components/blanket_cutters_star.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/center_column_cylinder.py, paramak/parametric_components/center_column_flat_top_circular.py, paramak/parametric_components/center_column_flat_top_hyperbola.py, paramak/parametric_components/center_column_hyperbola.py, paramak/parametric_components/center_column_plasma_dependant.py, paramak/parametric_components/coolant_channel_ring_curved.py, paramak/parametric_components/coolant_channel_ring_straight.py, paramak/parametric_components/cutting_wedge.py, paramak/parametric_components/inner_tf_coils_circular.py, paramak/parametric_components/inner_tf_coils_flat.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/poloidal_field_coil_case.py, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_princeton_d.py, paramak/parametric_components/toroidal_field_coil_rectangle.py, paramak/parametric_components/toroidal_field_coil_triple_arc.py
PR which adds type hinting to more parametric components via the method discussed in #648 
=> started adding type hinting to remaining components and shapes

.circleci/config.yml
Just changing the tag in the circle ci yml file to use the ukaea based docker image
=> using ukaea docker image

.github/workflows/dockerhub-publish-dependencies.yml
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
=> :whale: corrected dockerfile name

Dockerfile, DockerfileDependencies
This makes a few minor changes to the Dockerfiles. We were installing PYMOAB in an inefficient manner and actually installing it twice. So this should speed up the GitHub Action a little bit :+1: 
=> removed second pymoab install

.gitignore, paramak/parametric_neutronics/make_faceteted_neutronics_model.py, paramak/shape.py
Just a few more suggestions from code inspector
=> suggestions form code inspector

.circleci/config.yml, Dockerfile, DockerfileDependencies
Just changes the pip installs in the dockerfile to include vtk and removes some pip installs from the circle ci config file (because they are in the dockerfile)
=> changed pip installs in CI

.gitignore, Dockerfile, DockerfileDependencies
This just adds the curl apt to the docker images, this is needed when reporting the code coverage
Thanks to @RemDelaporteMathurin or spotting this
=> Add curl to dockerfiles

README.md, docs/source/index.rst, environment.yml
Adds a couple of links to the F1000 paper recently published. One link in the README.md and one in the index for the docs
=> Adding paper to docs

Dockerfile, paramak/utils.py, tests/test_utils.py
the name of the embree lib has changed, it use to be embree 3.12.1 but it is now embree 3.12.2
So some change to the double down build was needed
Also snuck in a new docstring for a cirle function
=> using embree 3.12.2

Dockerfile, DockerfileDependencies, examples/example_neutronics_simulations/component_based_mesh_simulation.py, paramak/parametric_neutronics/neutronics_model.py, setup.py, tests/test_parametric_neutronics/test_NeutronicModel.py
PR which documents the arguments related to 3D mesh tallies in neutronics_model.
fixes #687 
=> added documentation for 3d mesh arguments

README.md
Just adding a small cite to the README, I should also add it to the index.rst 
=> added cite section with bibtex

examples/example_parametric_reactors/htc_reactor.py, paramak/shape.py, tests/test_parametric_shapes/test_ExtrudeSplineShape.py, tests/test_parametric_shapes/test_ExtrudeStraightShape.py, tests/test_parametric_shapes/test_RotateSplineShape.py, tests/test_parametric_shapes/test_RotateStraightShape.py, tests/test_parametric_shapes/test_SweepCircleShape.py, tests/test_parametric_shapes/test_SweepSplineShape.py, tests/test_parametric_shapes/test_SweepStraightShape.py
Fixes bug #694 where one was able to make a parametric Shape with the connections specified by the user
=> Fixing points with connections bug

examples/example_parametric_components/make_all_parametric_components.py, examples/example_parametric_reactors/htc_reactor.py, examples/example_parametric_reactors/segmented_blanket_ball_reactor.py, paramak/parametric_components/poloidal_field_coil_case_set.py, paramak/parametric_components/poloidal_field_coil_case_set_fc.py, paramak/parametric_components/poloidal_field_coil_set.py, paramak/parametric_components/poloidal_segmenter.py, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_rectangle.py, paramak/parametric_shapes/sweep_circle_shape.py, paramak/reactor.py, paramak/shape.py, paramak/utils.py, tests/test_Shape.py, tests/test_parametric_shapes/test_ExtrudeStraightShape.py, tests/test_parametric_shapes/test_RotateMixedShape.py
This is progress towards getting the 2d image and 2d plotly graphs working.
They are still not quite perfect as they make use of the shape.face so I think they will remain a develop tool for checking the shapes and points look correct.
The reason they are not quite suitable for users is that the method does not account for boolean opperations prior to boolean operations.
However the main improvement is that the edges are now faceted for circles and splines with a controllable tolerance. This solves issue #84 
```python
import paramak
test_shape = paramak.RotateMixedShape(
points=[
(50, 0, "straight"),
(50, 50, "spline"),
(60, 70, "spline"),
(70, 50, "circle"),
(60, 25, "circle"),
(70, 0, "straight")
],
rotation_angle=10
)
test_shape.export_html()
test_shape.export_2d_image()
```
What …
=> Export html with facteted curves

paramak/shape.py, paramak/utils.py, tests/test_Shape.py
Just removing a test that was used to test the trace function in Shape.py. This function has now been removed
=> removed old _trace test

paramak/parametric_components/blanket_fp.py, paramak/parametric_components/blanket_poloidal_segment.py, paramak/parametric_shapes/extruded_circle_shape.py, paramak/reactor.py, paramak/shape.py, paramak/utils.py, tests/test_example_components.py, tests/test_neutronics_utils.py, tests/test_parametric_components/test_BlanketCutterParallels.py, tests/test_parametric_components/test_PortCutterRotated.py, tests/test_parametric_neutronics/test_Shape_neutronics.py
Resolving 13 comments from the pull request review, steady progress but still  plenty of improvements to implement. I think there are still 49 comments to go. Also the remaining comments are a little more tricky than the easier ones tackled here.
=> Pullrequest fixes from review

.github/workflows/docker_ci.yml, .gitignore, README.md, examples/example_parametric_reactors/make_animation.py, examples/example_parametric_shapes/make_CAD_from_points.py, paramak/parametric_neutronics/make_faceteted_neutronics_model.py, paramak/reactor.py, paramak/shape.py, tests/test_Reactor.py, tests/test_example_reactors.py, tests/test_parametric_shapes/test_RotateStraightShape.py
Adds improved svg export options such as width and height
=> Adding new CQ export svg features

paramak/shape.py
This removes the opening of a file and use of exporters.exportShape and replaces the stl with exporters.export as discussed in #82 
The former method is now depreciated.
Also slightly more control over the stl export is also offered via the introduction of a new argument called 
```angular_tolerance```
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
=> updated stl exporter to new cq method

examples/example_parametric_shapes/make_html_diagram_from_stp_file.py, paramak/shape.py, paramak/utils.py, tests/test_Shape.py, tests/test_example_shapes.py
Adds another workplane option to the html plotting of shapes. The new workplane is 'XYZ' which results in a 3D plot. This can also be used to load up stp files produced elsewhere and plot the coordinates (demonstrated in the updated example)
Updates include:
- additional tests
- updated example script
- a few docstrings that were missing
- a little more type hinting
- correction of tolerance that was being ignored by the function
example usage
```
import paramak
example_shape = paramak.ExtrudeMixedShape(
distance=1,
points=[
(100, 0, "straight"),
(200, 0, "circle"),
(250, 50, "circle"),
(200, 100, "straight"),
(150, 100, "spline"),
(140, 75, "spline"),
(110, 45, "spline"),
]
)
example_shape.export_html("graph.html", view_plane='XYZ')
```
External stp files can also be loaded up and …
=> New viewplane for html export

paramak/utils.py, tests/test_example_neutronics_simulations.py, tests/test_example_shapes.py, tests/test_parametric_shapes/test_ExtrudeStraightShape.py, tests/test_utils.py
Adds a few targeted tests to improve code coverage and other suggestions from the code inspector.com report https://github.com/ukaea/paramak/pull/726/checks?check_run_id=1871491648
=> Extra tests
